const DATA_KEY='tes_curriculum_v4',USER_KEY='tes_user_v4',SETTINGS_KEY='tes_settings_v4';
const DEFAULT_SUBJECTS=[['general','총론'],['korean','국어'],['ethics','도덕'],['social','사회'],['math','수학'],['science','과학'],['practical','실과'],['pe','체육'],['music','음악'],['art','미술'],['english','영어'],['integrated','통합교과']].map(([id,name])=>({id,name}));
const clone=v=>JSON.parse(JSON.stringify(v)),load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??clone(f)}catch{return clone(f)}},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const state={data:load(DATA_KEY,{schemaVersion:4,subjects:DEFAULT_SUBJECTS.map(s=>({...s,sections:[]}))}),user:load(USER_KEY,{itemState:{},rounds:{}}),settings:load(SETTINGS_KEY,{visibleSubjects:DEFAULT_SUBJECTS.map(s=>s.id),studySections:{},gradingMode:'flexible',aiProvider:'none'}),subjectId:'general',sectionId:null,itemId:null,view:'home',studyMode:'mask-edit',weaknessOnly:false,importFile:null};
function save(){localStorage.setItem(DATA_KEY,JSON.stringify(state.data));localStorage.setItem(USER_KEY,JSON.stringify(state.user));localStorage.setItem(SETTINGS_KEY,JSON.stringify(state.settings))}
function allSubjects(){const m=new Map(DEFAULT_SUBJECTS.map(s=>[s.id,s]));state.data.subjects.forEach(s=>m.set(s.id,{id:s.id,name:s.name}));return[...m.values()]}
function subjectData(id){return state.data.subjects.find(s=>s.id===id)}
function visibleSubjects(){return allSubjects().filter(s=>state.settings.visibleSubjects.includes(s.id))}
function enabledSectionIds(sub){const x=state.settings.studySections?.[sub.id];return Array.isArray(x)?x:(sub.sections||[]).map(s=>s.id)}
function enabledSections(sub){const ids=enabledSectionIds(sub);return(sub?.sections||[]).filter(s=>ids.includes(s.id))}
function currentSubject(){return subjectData(state.subjectId)}function currentSection(){return currentSubject()?.sections?.find(s=>s.id===state.sectionId)}function currentItem(){return currentSection()?.items?.find(i=>i.id===state.itemId)}
function ensureSelection(){const vis=visibleSubjects();if(!vis.some(s=>s.id===state.subjectId))state.subjectId=vis[0]?.id||null;const sub=currentSubject();if(!sub){state.sectionId=state.itemId=null;return}const secs=enabledSections(sub);if(!secs.some(s=>s.id===state.sectionId))state.sectionId=secs[0]?.id||null;const sec=currentSection();if(!sec?.items?.some(i=>i.id===state.itemId))state.itemId=sec?.items?.[0]?.id||null}
function mergeSections(target,incoming){const m=new Map((target.sections||[]).map(s=>[s.id,s]));(incoming.sections||[]).forEach(sec=>{const old=m.get(sec.id);m.set(sec.id,old?{...old,...sec,items:sec.items?.length?sec.items:(old.items||[])}:sec)});target.name=incoming.name||target.name;target.sections=[...m.values()]}
function mergeSubject(sub){let t=subjectData(sub.id);if(!t){state.data.subjects.push(sub);return}mergeSections(t,sub)}
async function loadBundled(){try{for(const path of ['./data/general/skeleton.json','./data/general/character.json']){const r=await fetch(path+'?v=4',{cache:'no-store'});if(!r.ok)continue;const b=await r.json();(b.subjects||[]).forEach(mergeSubject)}save()}catch(e){console.warn(e)}}
function allEnabledItems(sub){return enabledSections(sub).flatMap(sec=>(sec.items||[]).map(item=>({sec,item})))}
function roundState(id){state.user.rounds[id]??={count:0,completed:[]};return state.user.rounds[id]}
function roundProgress(sub){const r=roundState(sub.id),all=allEnabledItems(sub).map(x=>x.item.id),done=all.filter(id=>r.completed.includes(id)).length;return{count:r.count,done,total:all.length,pct:all.length?Math.round(done/all.length*100):0}}
function markComplete(id){const sub=currentSubject(),r=roundState(sub.id);if(!r.completed.includes(id))r.completed.push(id);const all=allEnabledItems(sub).map(x=>x.item.id);if(all.length&&all.every(x=>r.completed.includes(x))){r.count++;r.completed=[];alert(`${sub.name} ${r.count}회독 완료!`)}save();render()}
function render(){ensureSelection();renderSubjectBar();renderSectionBar();updateWeaknessBadge();if(state.view==='home')renderHome();else if(state.view==='weakness')renderWeakness();else if(state.view==='study')renderStudy();else renderReader()}
function renderSubjectBar(){const bar=$('#subjectBar');bar.innerHTML=visibleSubjects().map(s=>`<button class="nav-tab ${s.id===state.subjectId?'active':''}" data-subject="${s.id}">${esc(s.name)}</button>`).join('');$$('[data-subject]').forEach(b=>b.onclick=()=>{state.subjectId=b.dataset.subject;state.sectionId=state.itemId=null;state.view='reader';render()})}
function renderSectionBar(){const sub=currentSubject(),bar=$('#sectionBar');if(!sub){bar.innerHTML='';return}bar.innerHTML=enabledSections(sub).map(s=>`<button class="nav-tab ${s.id===state.sectionId?'active':''}" data-section="${s.id}">${esc(s.name)}</button>`).join('');$$('[data-section]').forEach(b=>b.onclick=()=>{state.sectionId=b.dataset.section;state.itemId=null;state.view='reader';render()})}
function renderHome(){const cards=visibleSubjects().map(s=>{const sub=subjectData(s.id),p=sub?roundProgress(sub):{count:0,done:0,total:0,pct:0};return`<article class="card round-card"><div class="round-card-head"><strong>${esc(s.name)}</strong><span>${p.count}회독</span></div><div class="round-progress"><i style="width:${p.pct}%"></i></div><p>${p.done}/${p.total} 항목 · ${p.pct}%</p><button class="ghost-btn" data-open-sub="${s.id}">열기</button></article>`}).join('');$('#appMain').innerHTML=`<section class="hero"><div><span class="eyebrow">Curriculum Study</span><h1>교육과정 학습 현황</h1><p>과목별 회독과 현재 회독 진행률을 확인하세요.</p></div></section><div class="round-grid">${cards}</div>`;$$('[data-open-sub]').forEach(b=>b.onclick=()=>{state.subjectId=b.dataset.openSub;state.sectionId=state.itemId=null;state.view='reader';render()})}
function renderSegments(seg=[]){return seg.map(s=>`<span class="${s.highlight?'source-highlight':''}">${esc(s.text)}</span>`).join('')}
function renderTable(b){const occ=new Set(),m=new Map((b.cells||[]).map(c=>[`${c.row}:${c.col}`,c]));let h='<div class="table-scroll"><table class="source-table"><tbody>';for(let r=0;r<(b.rows||0);r++){h+='<tr>';for(let c=0;c<(b.cols||0);c++){if(occ.has(`${r}:${c}`))continue;const cell=m.get(`${r}:${c}`);if(!cell){h+='<td></td>';continue}for(let rr=r;rr<r+(cell.rowspan||1);rr++)for(let cc=c;cc<c+(cell.colspan||1);cc++)if(rr!==r||cc!==c)occ.add(`${rr}:${cc}`);h+=`<td rowspan="${cell.rowspan||1}" colspan="${cell.colspan||1}">${renderSegments(cell.segments)}</td>`}h+='</tr>'}return h+'</tbody></table></div>'}
function renderBlocks(item){if(!item?.blocks?.length)return`<div class="original-text">${esc(item?.originalText||'')}</div>`;return`<div class="source-document">${item.blocks.map(b=>b.type==='table'?renderTable(b):`<p>${renderSegments(b.segments)}</p>`).join('')}</div>`}
function renderReader(){const sub=currentSubject(),sec=currentSection(),item=currentItem(),rp=sub?roundProgress(sub):{count:0,done:0,total:0};if(!sub)return renderHome();const items=sec?.items||[];$('#appMain').innerHTML=`<section class="hero compact"><div><span class="eyebrow">${esc(sub.name)}</span><h1>${esc(sec?.name||'영역 없음')}</h1><p>${sec?.group?`구분: ${esc(sec.group)}`:''}</p></div><div class="round-mini"><strong>${rp.count}회독</strong><span>${rp.done}/${rp.total}</span></div></section><div class="content-layout"><aside class="card toc"><div class="toc-title">세부 목차</div>${items.map(i=>`<button class="${i.id===state.itemId?'active':''}" data-item="${i.id}">${esc(i.title||'제목 없음')}</button>`).join('')||'<div class="empty-state small">이 영역은 아직 자료 변환 전입니다.</div>'}</aside><article class="card reader">${item?`<div class="breadcrumb">${esc(sub.name)} / ${esc(sec.name)}</div><div class="reader-heading"><div><h1>${esc(item.title||'원문')}</h1></div><span class="highlight-legend"><i></i> 원문 강조</span></div>${renderBlocks(item)}<div class="reader-actions"><button id="completeItemBtn" class="ghost-btn">학습 완료</button><button id="maskStartBtn" class="soft-btn">가리기 설정</button><button id="typingStartBtn" class="primary-btn">타이핑 학습</button></div>`:`<div class="empty-state"><h2>${esc(sec?.name||'이 영역')}</h2><p>아직 내용이 없습니다. 과목별 자료 업로드에서 변환된 JSON을 넣으면 이곳에 채워집니다.</p><button id="readerUploadBtn" class="primary-btn">${esc(sub.name)} 자료 업로드</button></div>`}</article></div>`;$$('[data-item]').forEach(b=>b.onclick=()=>{state.itemId=b.dataset.item;render()});if(item){$('#completeItemBtn').onclick=()=>markComplete(item.id);$('#maskStartBtn').onclick=()=>{state.studyMode='mask-edit';state.view='study';render()};$('#typingStartBtn').onclick=()=>{state.studyMode='typing';state.view='study';render()}}else if($('#readerUploadBtn'))$('#readerUploadBtn').onclick=()=>openImportDialog(sub.id)}
function tokenize(text){return String(text||'').split(/(\s+)/).map((text,index)=>({index,text,isSpace:/^\s+$/.test(text)}))}
function itemState(id){state.user.itemState[id]??={masked:[],wrongTokens:[],wrongCount:0};return state.user.itemState[id]}
function norm(v){return String(v||'').toLowerCase().replace(/[\s.,!?;:'"“”‘’·⋅()\[\]{}<>/\\\-_~`]+/g,'')}
function sourceIndexes(item){const terms=new Set((item.highlightWords||[]).map(norm));return tokenize(item.originalText).filter(t=>!t.isSpace&&terms.has(norm(t.text))).map(t=>t.index)}
function renderStudy(){const item=currentItem();if(!item){state.view='reader';return render()}const u=itemState(item.id),sub=currentSubject(),sec=currentSection();$('#appMain').innerHTML=`<article class="card study-card"><div class="study-titlebar"><div><span class="eyebrow">${esc(sub.name)} · ${esc(sec.name)}</span><h2>${esc(item.title||'학습')}</h2></div><div class="mode-switch"><button data-mode="mask-edit" class="${state.studyMode==='mask-edit'?'active':''}">가리기 설정</button><button data-mode="mask-study" class="${state.studyMode==='mask-study'?'active':''}">가리기 학습</button><button data-mode="typing" class="${state.studyMode==='typing'?'active':''}">타이핑</button></div></div><div id="studyContent"></div><div class="study-footer"><button id="backReaderBtn" class="ghost-btn">원문으로</button><div id="studyFooterRight"></div></div></article>`;$$('[data-mode]').forEach(b=>b.onclick=()=>{state.studyMode=b.dataset.mode;state.weaknessOnly=false;renderStudy()});$('#backReaderBtn').onclick=()=>{state.view='reader';render()};if(state.studyMode==='mask-edit')renderMaskEditor(item,u);else if(state.studyMode==='mask-study')renderMaskStudy(item,u);else renderTyping(item,u)}
function renderMaskEditor(item,u){const ts=tokenize(item.originalText),src=sourceIndexes(item);$('#studyContent').innerHTML=`<div class="helper">암기할 어절을 터치하세요.</div><div class="token-editor">${ts.map(t=>t.isSpace?esc(t.text):`<span class="token selectable ${u.masked.includes(t.index)?'selected':''} ${src.includes(t.index)?'source-token':''}" data-token="${t.index}">${esc(t.text)}</span>`).join('')}</div>`;$('#studyFooterRight').innerHTML='<button id="redAll" class="ghost-btn">붉은 강조 모두 선택</button> <button id="maskGo" class="primary-btn">학습 시작</button>';$$('[data-token]').forEach(el=>el.onclick=()=>{const x=Number(el.dataset.token);u.masked=u.masked.includes(x)?u.masked.filter(v=>v!==x):[...u.masked,x].sort((a,b)=>a-b);save();renderMaskEditor(item,u)});$('#redAll').onclick=()=>{u.masked=[...new Set([...u.masked,...src])];save();renderMaskEditor(item,u)};$('#maskGo').onclick=()=>{state.studyMode='mask-study';renderStudy()}}
function renderMaskStudy(item,u){const ts=tokenize(item.originalText),mask=state.weaknessOnly&&u.wrongTokens.length?u.wrongTokens:u.masked;if(!mask.length){$('#studyContent').innerHTML='<div class="empty-state"><h2>가리기 설정이 필요합니다.</h2></div>';return}$('#studyContent').innerHTML=`<div class="mask-study">${ts.map(t=>t.isSpace?esc(t.text):`<span class="token ${mask.includes(t.index)?'masked':''}" data-reveal="${t.index}">${esc(t.text)}</span>`).join('')}</div>`;$('#studyFooterRight').innerHTML='<button id="doneStudy" class="primary-btn">학습 완료</button>';$$('[data-reveal]').forEach(e=>e.onclick=()=>e.classList.toggle('revealed'));$('#doneStudy').onclick=()=>markComplete(item.id)}
function grade(expected,actual){if(state.settings.gradingMode==='strict')return actual.trim()===expected.trim();if(state.settings.gradingMode==='self')return null;return norm(actual)===norm(expected)}
function renderTyping(item,u){const ts=tokenize(item.originalText),mask=state.weaknessOnly&&u.wrongTokens.length?u.wrongTokens:u.masked;if(!mask.length){$('#studyContent').innerHTML='<div class="empty-state"><h2>가리기 설정에서 빈칸을 먼저 정해주세요.</h2></div>';return}let n=0;$('#studyContent').innerHTML=`<div class="helper">빈칸에 답만 입력하고 Enter 또는 다음 칸으로 이동하면 자동 채점됩니다.</div><div class="typing-inline">${ts.map(t=>{if(t.isSpace)return esc(t.text);if(!mask.includes(t.index))return esc(t.text);const k=n++;return`<input class="inline-answer" data-token="${t.index}" style="width:${Math.max(72,Math.min(230,t.text.length*22+25))}px">`}).join('')}</div><div id="typingResult"></div>`;const inputs=$$('.inline-answer');inputs.forEach((input,i)=>{const check=()=>{if(!input.value.trim())return;const idx=Number(input.dataset.token),expected=ts.find(t=>t.index===idx)?.text||'',ok=grade(expected,input.value);input.classList.remove('input-correct','input-wrong','input-self');if(ok===null)input.classList.add('input-self');else if(ok){input.classList.add('input-correct');u.wrongTokens=u.wrongTokens.filter(x=>x!==idx)}else{input.classList.add('input-wrong');if(!u.wrongTokens.includes(idx))u.wrongTokens.push(idx);u.wrongCount=(u.wrongCount||0)+1}save();updateWeaknessBadge()};input.onblur=check;input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();check();inputs[i+1]?.focus()}}});$('#studyFooterRight').innerHTML='<button id="typingDone" class="primary-btn">학습 완료</button>';$('#typingDone').onclick=()=>markComplete(item.id);inputs[0]?.focus()}
function findItem(id){for(const subject of state.data.subjects)for(const section of subject.sections||[]){const item=(section.items||[]).find(i=>i.id===id);if(item)return{subject,section,item}}return null}
function weaknessEntries(){return Object.entries(state.user.itemState).filter(([,u])=>u.wrongTokens?.length).map(([id,u])=>({id,u,found:findItem(id)})).filter(x=>x.found)}
function updateWeaknessBadge(){const b=$('#weaknessBadge'),n=weaknessEntries().length;if(!b)return;b.textContent=n;b.classList.toggle('hidden',!n)}
function renderWeakness(){const es=weaknessEntries();$('#appMain').innerHTML=`<section class="hero"><div><span class="eyebrow">Weakness Review</span><h1>약점 보충</h1><p>틀린 어절만 다시 공부합니다.</p></div></section>${es.length?`<div class="weakness-grid">${es.map(({id,u,found})=>`<article class="card weak-card"><div><span class="weak-meta">${esc(found.subject.name)} · ${esc(found.section.name)}</span><h3>${esc(found.item.title)}</h3><p>남은 약점 ${u.wrongTokens.length}개</p></div><button class="primary-btn" data-weak="${id}">타이핑 재도전</button></article>`).join('')}</div>`:'<div class="card empty-state"><h2>현재 약점이 없습니다.</h2></div>'}`;$$('[data-weak]').forEach(b=>b.onclick=()=>{const f=findItem(b.dataset.weak);state.subjectId=f.subject.id;state.sectionId=f.section.id;state.itemId=f.item.id;state.weaknessOnly=true;state.studyMode='typing';state.view='study';render()})}
function renderSettings(){$('#subjectSettings').innerHTML=allSubjects().map(s=>`<label class="check-row"><input type="checkbox" value="${s.id}" ${state.settings.visibleSubjects.includes(s.id)?'checked':''}> ${esc(s.name)}</label>`).join('');$('#areaSettings').innerHTML=allSubjects().map(s=>{const sub=subjectData(s.id),secs=sub?.sections||[],enabled=enabledSectionIds(sub||{id:s.id,sections:[]});return`<div class="area-subject"><div class="area-subject-title">${esc(s.name)}</div>${secs.length?`<div class="area-checks">${secs.map(sec=>`<label class="check-row"><input type="checkbox" data-area-subject="${s.id}" value="${sec.id}" ${enabled.includes(sec.id)?'checked':''}> ${esc(sec.name)}</label>`).join('')}</div>`:'<p class="muted small-text">업로드된 영역 없음</p>'}</div>`}).join('');$$('input[name="gradingMode"]').forEach(r=>r.checked=r.value===state.settings.gradingMode);$('#aiProvider').value=state.settings.aiProvider||'none'}
function openImportDialog(subjectId=state.subjectId){$('#importSubject').innerHTML=allSubjects().map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');$('#importSubject').value=subjectId||'general';state.importFile=null;$('#selectedFileName').textContent='아직 선택된 파일이 없습니다.';$('#importFile').value='';$('#importDialog').showModal()}
function payloadForSubject(p,subjectId){if(Array.isArray(p.subjects)){const found=p.subjects.find(s=>s.id===subjectId);if(found)return found;if(p.subjects.length===1)return{...p.subjects[0],id:subjectId,name:subjectData(subjectId)?.name||p.subjects[0].name}}if(Array.isArray(p.sections))return{id:subjectId,name:subjectData(subjectId)?.name||subjectId,sections:p.sections};throw new Error('앱용 교육과정 JSON 형식을 찾지 못했습니다.')}
$('#homeBtn').onclick=()=>{state.view='home';render()};$('#weaknessBtn').onclick=()=>{state.view='weakness';render()};$('#importBtn').onclick=()=>openImportDialog();$('#importFile').onchange=e=>{state.importFile=e.target.files[0]||null;$('#selectedFileName').textContent=state.importFile?state.importFile.name:'아직 선택된 파일이 없습니다.'};$('#doImportBtn').onclick=async()=>{if(!state.importFile)return alert('JSON 파일을 선택해주세요.');try{const p=JSON.parse(await state.importFile.text()),sid=$('#importSubject').value,sub=payloadForSubject(p,sid);mergeSubject(sub);save();$('#importDialog').close();state.subjectId=sid;state.sectionId=state.itemId=null;state.view='reader';render();alert('선택한 과목에 자료를 업로드했습니다.')}catch(e){alert(e.message||'파일을 읽지 못했습니다.')}};$('#settingsBtn').onclick=()=>{renderSettings();$('#settingsDialog').showModal()};$('#saveSettingsBtn').onclick=()=>{const checked=$$('#subjectSettings input:checked').map(i=>i.value);state.settings.visibleSubjects=checked.length?checked:['general'];state.settings.studySections={};$$('[data-area-subject]').forEach(i=>{state.settings.studySections[i.dataset.areaSubject]??=[];if(i.checked)state.settings.studySections[i.dataset.areaSubject].push(i.value)});state.settings.gradingMode=$('input[name="gradingMode"]:checked')?.value||'flexible';state.settings.aiProvider=$('#aiProvider').value;save();$('#settingsDialog').close();render()};
(async()=>{await loadBundled();render()})();