const DATA_KEY='tes_curriculum_v3';
const USER_KEY='tes_user_v3';
const SETTINGS_KEY='tes_settings_v3';
const BUNDLE_MARKER_KEY='tes_bundle_marker_v3';
const BUNDLE_MARKER='general-solli-20260824-3';

const DEFAULT_SUBJECTS=[
 {id:'general',name:'총론'},{id:'korean',name:'국어'},{id:'ethics',name:'도덕'},{id:'social',name:'사회'},
 {id:'math',name:'수학'},{id:'science',name:'과학'},{id:'practical',name:'실과'},{id:'pe',name:'체육'},
 {id:'music',name:'음악'},{id:'art',name:'미술'},{id:'english',name:'영어'},{id:'integrated',name:'통합교과'}
];
const EMPTY_DATA={schemaVersion:3,contentType:'curriculum',subjects:DEFAULT_SUBJECTS.map(s=>({...s,sections:[]}))};
const clone=v=>JSON.parse(JSON.stringify(v));
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??clone(f)}catch{return clone(f)}}
const state={
 data:load(DATA_KEY,EMPTY_DATA),
 user:load(USER_KEY,{itemState:{},rounds:{}}),
 settings:load(SETTINGS_KEY,{visibleSubjects:DEFAULT_SUBJECTS.map(s=>s.id),studySections:{},gradingMode:'flexible',aiProvider:'none'}),
 subjectId:'general',sectionId:null,itemId:null,view:'home',studyMode:'mask-edit',weaknessOnly:false
};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function save(){localStorage.setItem(DATA_KEY,JSON.stringify(state.data));localStorage.setItem(USER_KEY,JSON.stringify(state.user));localStorage.setItem(SETTINGS_KEY,JSON.stringify(state.settings))}
function allSubjects(){const m=new Map(DEFAULT_SUBJECTS.map(s=>[s.id,s]));state.data.subjects.forEach(s=>m.set(s.id,{id:s.id,name:s.name}));return [...m.values()]}
function subjectData(id){return state.data.subjects.find(s=>s.id===id)}
function visibleSubjects(){return allSubjects().filter(s=>state.settings.visibleSubjects.includes(s.id))}
function enabledSectionIds(subject){const stored=state.settings.studySections?.[subject.id];if(Array.isArray(stored))return stored;return(subject.sections||[]).map(s=>s.id)}
function enabledSections(subject){const ids=enabledSectionIds(subject);return(subject?.sections||[]).filter(s=>ids.includes(s.id))}
function currentSubject(){return subjectData(state.subjectId)}
function currentSection(){return currentSubject()?.sections?.find(s=>s.id===state.sectionId)}
function currentItem(){return currentSection()?.items?.find(i=>i.id===state.itemId)}
function ensureSelection(){const vis=visibleSubjects();if(!vis.some(s=>s.id===state.subjectId))state.subjectId=vis[0]?.id||null;const sub=currentSubject();if(!sub){state.sectionId=state.itemId=null;return}const secs=enabledSections(sub);if(!secs.some(s=>s.id===state.sectionId))state.sectionId=secs[0]?.id||null;const sec=currentSection();if(!sec?.items?.some(i=>i.id===state.itemId))state.itemId=sec?.items?.[0]?.id||null}
function mergeSubject(subject,replace=true){const i=state.data.subjects.findIndex(s=>s.id===subject.id);if(i>=0&&replace)state.data.subjects[i]=subject;else if(i<0)state.data.subjects.push(subject)}
async function loadBundledData(){if(localStorage.getItem(BUNDLE_MARKER_KEY)===BUNDLE_MARKER)return;const files=['character','chapter-1','chapter-2','chapter-3','chapter-4'];try{const subject={id:'general',name:'총론',sections:[]};for(const name of files){const r=await fetch(`./data/general/${name}.json?v=3`,{cache:'no-store'});if(!r.ok)throw new Error(`bundle missing: ${name}`);const b=await r.json();const s=(b.subjects||[]).find(x=>x.id==='general');if(s?.sections?.[0])subject.sections.push(s.sections[0])}mergeSubject(subject,true);localStorage.setItem(BUNDLE_MARKER_KEY,BUNDLE_MARKER);save()}catch(e){console.warn(e)}}
function allEnabledItems(subject){return enabledSections(subject).flatMap(sec=>(sec.items||[]).map(item=>({sec,item})))}
function roundState(subjectId){state.user.rounds[subjectId]??={count:0,completed:[]};return state.user.rounds[subjectId]}
function markItemComplete(itemId){const sub=currentSubject();if(!sub)return;const r=roundState(sub.id);if(!r.completed.includes(itemId))r.completed.push(itemId);const all=allEnabledItems(sub).map(x=>x.item.id);if(all.length&&all.every(id=>r.completed.includes(id))){r.count+=1;r.completed=[];alert(`${sub.name} ${r.count}회독 완료!`)}save();render()}
function roundProgress(subject){const r=roundState(subject.id),all=allEnabledItems(subject).map(x=>x.item.id),done=all.filter(id=>r.completed.includes(id)).length;return{count:r.count,done,total:all.length,pct:all.length?Math.round(done/all.length*100):0}}
function render(){ensureSelection();renderSubjectBar();renderSectionBar();updateWeaknessBadge();if(state.view==='home')renderHome();else if(state.view==='weakness')renderWeakness();else if(state.view==='study')renderStudy();else renderReader()}
function renderSubjectBar(){const bar=$('#subjectBar');bar.innerHTML=visibleSubjects().map(s=>`<button class="nav-tab ${s.id===state.subjectId?'active':''}" data-subject="${esc(s.id)}">${esc(s.name)}</button>`).join('');bar.querySelectorAll('[data-subject]').forEach(b=>b.onclick=()=>{state.subjectId=b.dataset.subject;state.sectionId=state.itemId=null;state.view='reader';state.weaknessOnly=false;render()})}
function renderSectionBar(){const sub=currentSubject(),bar=$('#sectionBar');if(!sub){bar.innerHTML='';return}bar.innerHTML=enabledSections(sub).map(s=>`<button class="nav-tab ${s.id===state.sectionId?'active':''}" data-section="${esc(s.id)}">${esc(s.name)}</button>`).join('');bar.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{state.sectionId=b.dataset.section;state.itemId=null;state.view='reader';render()})}
function countItems(){return state.data.subjects.reduce((a,s)=>a+(s.sections||[]).reduce((b,sec)=>b+(sec.items?.length||0),0),0)}
function renderHome(){const cards=visibleSubjects().map(s=>{const sub=subjectData(s.id),p=sub?roundProgress(sub):{count:0,done:0,total:0,pct:0};return`<article class="card round-card"><div class="round-card-head"><strong>${esc(s.name)}</strong><span>${p.count}회독</span></div><div class="round-progress"><i style="width:${p.pct}%"></i></div><p>${p.done} / ${p.total} 항목 · 현재 회독 ${p.pct}%</p><button class="ghost-btn" data-open-subject="${esc(s.id)}">열기</button></article>`}).join('');$('#appMain').innerHTML=`<section class="hero"><div><span class="eyebrow">Curriculum Study</span><h1>교육과정 학습 현황</h1><p>과목별 회독과 현재 회독 진행률을 확인할 수 있습니다.</p></div></section><div class="metric-row"><article class="card metric"><span>등록 원문</span><strong>${countItems()}</strong></article><article class="card metric"><span>학습 과목</span><strong>${visibleSubjects().length}</strong></article><article class="card metric"><span>약점 항목</span><strong>${weaknessEntries().length}</strong></article></div><section><h2 class="section-title">과목별 회독</h2><div class="round-grid">${cards}</div></section>`;$$('[data-open-subject]').forEach(b=>b.onclick=()=>{state.subjectId=b.dataset.openSubject;state.sectionId=state.itemId=null;state.view='reader';render()})}
function renderSegments(seg=[]){return seg.map(s=>`<span class="${s.highlight?'source-highlight':''}">${esc(s.text)}</span>`).join('')}
function renderTable(block){const occ=new Set(),m=new Map((block.cells||[]).map(c=>[`${c.row}:${c.col}`,c]));let h='<div class="table-scroll"><table class="source-table"><tbody>';for(let r=0;r<(block.rows||0);r++){h+='<tr>';for(let c=0;c<(block.cols||0);c++){if(occ.has(`${r}:${c}`))continue;const cell=m.get(`${r}:${c}`);if(!cell){h+='<td></td>';continue}for(let rr=r;rr<r+(cell.rowspan||1);rr++)for(let cc=c;cc<c+(cell.colspan||1);cc++)if(rr!==r||cc!==c)occ.add(`${rr}:${cc}`);h+=`<td rowspan="${cell.rowspan||1}" colspan="${cell.colspan||1}">${renderSegments(cell.segments)}</td>`}h+='</tr>'}return h+'</tbody></table></div>'}
function renderBlocks(item){if(!item?.blocks?.length)return`<div class="original-text">${esc(item?.originalText||'')}</div>`;return`<div class="source-document">${item.blocks.map(b=>b.type==='table'?renderTable(b):`<p>${renderSegments(b.segments)}</p>`).join('')}</div>`}
function renderReader(){const sub=currentSubject(),sec=currentSection(),item=currentItem();if(!sub)return renderHome();const items=sec?.items||[],rp=roundProgress(sub);$('#appMain').innerHTML=`<section class="hero compact"><div><span class="eyebrow">${esc(sub.name)}</span><h1>${esc(sec?.name||'선택된 영역 없음')}</h1><p>이 영역의 원문을 항목별로 학습합니다.</p></div><div class="round-mini"><strong>${rp.count}회독</strong><span>${rp.done}/${rp.total}</span></div></section><div class="content-layout"><aside class="card toc"><div class="toc-title">세부 목차</div>${items.map(i=>`<button class="${i.id===state.itemId?'active':''}" data-item="${esc(i.id)}">${esc(i.title||'제목 없음')}</button>`).join('')||'<div class="empty-state small">자료 없음</div>'}</aside><article class="card reader">${item?`<div class="breadcrumb">${esc(sub.name)} / ${esc(sec.name)}</div><div class="reader-heading"><div><h1>${esc(item.title||'교육과정 원문')}</h1><p class="reader-note">붉은 글자는 원본 HWPX의 강조를 보존한 것입니다.</p></div><span class="highlight-legend"><i></i> 원문 강조</span></div>${renderBlocks(item)}<div class="reader-actions"><button id="completeItemBtn" class="ghost-btn">이 항목 학습 완료</button><button id="maskStartBtn" class="soft-btn">가리기 설정</button><button id="typingStartBtn" class="primary-btn">타이핑 학습</button></div>`:`<div class="empty-state"><h2>이 영역에 자료가 없습니다.</h2></div>`}</article></div>`;$$('[data-item]').forEach(b=>b.onclick=()=>{state.itemId=b.dataset.item;render()});if(item){$('#completeItemBtn').onclick=()=>markItemComplete(item.id);$('#maskStartBtn').onclick=()=>{state.studyMode='mask-edit';state.view='study';render()};$('#typingStartBtn').onclick=()=>{state.studyMode='typing';state.view='study';render()}}}
function tokenize(text){return String(text||'').split(/(\s+)/).map((text,index)=>({index,text,isSpace:/^\s+$/.test(text)}))}
function itemUserState(id){state.user.itemState[id]??={masked:[],attempts:0,correct:0,wrongTokens:[],wrongCount:0};state.user.itemState[id].wrongTokens??=[];return state.user.itemState[id]}
function normalizeWord(v){return String(v||'').toLowerCase().replace(/[\s.,!?;:'"“”‘’·⋅()\[\]{}<>/\\\-_~`]+/g,'')}
function highlightedTokenIndexes(item){const terms=new Set((item.highlightWords||[]).map(normalizeWord).filter(Boolean));return tokenize(item.originalText).filter(t=>!t.isSpace&&terms.has(normalizeWord(t.text))).map(t=>t.index)}
function renderStudy(){const item=currentItem();if(!item){state.view='reader';return render()}const u=itemUserState(item.id),sub=currentSubject(),sec=currentSection();$('#appMain').innerHTML=`<article class="card study-card"><div class="study-titlebar"><div><span class="eyebrow">${esc(sub.name)} · ${esc(sec.name)}</span><h2>${esc(item.title||'학습')}</h2></div><div class="mode-switch"><button data-mode="mask-edit" class="${state.studyMode==='mask-edit'?'active':''}">가리기 설정</button><button data-mode="mask-study" class="${state.studyMode==='mask-study'?'active':''}">가리기 학습</button><button data-mode="typing" class="${state.studyMode==='typing'?'active':''}">타이핑</button></div></div><div id="studyContent"></div><div class="study-footer"><button id="backReaderBtn" class="ghost-btn">원문으로 돌아가기</button><div id="studyFooterRight"></div></div></article>`;$$('[data-mode]').forEach(b=>b.onclick=()=>{state.studyMode=b.dataset.mode;state.weaknessOnly=false;renderStudy()});$('#backReaderBtn').onclick=()=>{state.view='reader';state.weaknessOnly=false;render()};if(state.studyMode==='mask-edit')renderMaskEditor(item,u);if(state.studyMode==='mask-study')renderMaskStudy(item,u);if(state.studyMode==='typing')renderTyping(item,u)}
function renderMaskEditor(item,u){const ts=tokenize(item.originalText),src=highlightedTokenIndexes(item);$('#studyContent').innerHTML=`<div class="helper">암기할 <strong>어절을 터치</strong>하세요. 빨간 글자만 한 번에 선택할 수도 있습니다.</div><div class="token-editor">${ts.map(t=>t.isSpace?esc(t.text):`<span class="token selectable ${u.masked.includes(t.index)?'selected':''} ${src.includes(t.index)?'source-token':''}" data-token="${t.index}">${esc(t.text)}</span>`).join('')}</div>`;$('#studyFooterRight').innerHTML='<button id="redSelectBtn" class="ghost-btn">붉은 강조 모두 선택</button> <button id="clearMasksBtn" class="ghost-btn">전체 해제</button> <button id="goMaskStudyBtn" class="primary-btn">학습 시작</button>';$$('[data-token]').forEach(el=>el.onclick=()=>{const x=Number(el.dataset.token);u.masked=u.masked.includes(x)?u.masked.filter(v=>v!==x):[...u.masked,x].sort((a,b)=>a-b);save();renderMaskEditor(item,u)});$('#redSelectBtn').onclick=()=>{u.masked=[...new Set([...u.masked,...src])].sort((a,b)=>a-b);save();renderMaskEditor(item,u)};$('#clearMasksBtn').onclick=()=>{u.masked=[];save();renderMaskEditor(item,u)};$('#goMaskStudyBtn').onclick=()=>{state.studyMode='mask-study';renderStudy()}}
function renderMaskStudy(item,u){if(!u.masked.length){$('#studyContent').innerHTML='<div class="empty-state"><h2>가릴 어절이 없어요.</h2></div>';$('#studyFooterRight').innerHTML='<button id="setupMaskBtn" class="primary-btn">가리기 설정</button>';$('#setupMaskBtn').onclick=()=>{state.studyMode='mask-edit';renderStudy()};return}const ts=tokenize(item.originalText);$('#studyContent').innerHTML=`<div class="helper">가려진 어절을 터치하면 하나씩 공개됩니다.</div><div class="mask-study">${ts.map(t=>t.isSpace?esc(t.text):`<span class="token ${u.masked.includes(t.index)?'masked':''}" data-reveal="${t.index}">${esc(t.text)}</span>`).join('')}</div>`;$('#studyFooterRight').innerHTML='<button id="revealAllBtn" class="ghost-btn">모두 공개</button> <button id="maskDoneBtn" class="primary-btn">이 항목 학습 완료</button>';$$('[data-reveal]').forEach(el=>el.onclick=()=>el.classList.toggle('revealed'));$('#revealAllBtn').onclick=()=>$$('.token.masked').forEach(x=>x.classList.add('revealed'));$('#maskDoneBtn').onclick=()=>markItemComplete(item.id)}
function gradeExpected(expected,actual){if(state.settings.gradingMode==='strict')return actual.trim()===expected.trim();if(state.settings.gradingMode==='self')return null;return normalizeWord(actual)===normalizeWord(expected)}
function gradeOneInput(input,item,u){if(!input.value.trim())return;const tokenIndex=Number(input.dataset.tokenIndex),expected=tokenize(item.originalText).find(t=>t.index===tokenIndex)?.text||'',ok=gradeExpected(expected,input.value);input.classList.remove('input-correct','input-wrong');if(ok===null){input.classList.add('input-self');return}u.attempts=(u.attempts||0)+1;if(ok){input.classList.add('input-correct');u.wrongTokens=u.wrongTokens.filter(x=>x!==tokenIndex)}else{input.classList.add('input-wrong');if(!u.wrongTokens.includes(tokenIndex))u.wrongTokens.push(tokenIndex);u.wrongCount=(u.wrongCount||0)+1}input.dataset.graded='true';save();updateWeaknessBadge();updateTypingSummary(u)}
function updateTypingSummary(u){const ins=$$('.inline-answer'),graded=ins.filter(i=>i.dataset.graded==='true'),correct=graded.filter(i=>i.classList.contains('input-correct')).length,res=$('#typingResult');if(!res)return;res.innerHTML=graded.length?`<div class="result-box ${correct===graded.length?'good':'bad'}"><strong>${correct} / ${graded.length}</strong> 현재 채점 · 오답은 약점 보충에 자동 저장됩니다.</div>`:''}
function renderTyping(item,u){let mask=state.weaknessOnly&&u.wrongTokens.length?u.wrongTokens:u.masked;if(!mask.length){$('#studyContent').innerHTML='<div class="empty-state"><h2>먼저 암기할 부분을 선택해 주세요.</h2></div>';$('#studyFooterRight').innerHTML='<button id="typingSetupBtn" class="primary-btn">가리기 설정</button>';$('#typingSetupBtn').onclick=()=>{state.studyMode='mask-edit';renderStudy()};return}const ts=tokenize(item.originalText);let n=0;const prompt=ts.map(t=>{if(t.isSpace)return esc(t.text);if(!mask.includes(t.index))return`<span>${esc(t.text)}</span>`;const k=n++,w=Math.max(72,Math.min(230,t.text.length*22+25));return`<input class="inline-answer" data-answer-index="${k}" data-token-index="${t.index}" style="width:${w}px" autocomplete="off" spellcheck="false">`}).join('');$('#studyContent').innerHTML=`<div class="helper"><strong>${state.settings.gradingMode==='strict'?'엄격 채점':state.settings.gradingMode==='self'?'직접 확인':'유연 채점'}</strong> · 빈칸에 답만 입력하고 Enter 또는 다음 칸으로 이동하면 자동 채점됩니다.</div><div class="typing-inline">${prompt}</div><div id="typingResult"></div>`;$('#studyFooterRight').innerHTML='<button id="checkRemainingBtn" class="ghost-btn">입력한 답 전체 확인</button> <button id="typingDoneBtn" class="primary-btn">이 항목 학습 완료</button>';const ins=$$('.inline-answer');ins.forEach((input,i)=>{input.addEventListener('blur',()=>gradeOneInput(input,item,u));input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();gradeOneInput(input,item,u);ins[i+1]?.focus()}})});$('#checkRemainingBtn').onclick=()=>ins.forEach(x=>gradeOneInput(x,item,u));$('#typingDoneBtn').onclick=()=>markItemComplete(item.id);ins[0]?.focus()}
function findItem(id){for(const subject of state.data.subjects)for(const section of subject.sections||[]){const item=(section.items||[]).find(i=>i.id===id);if(item)return{subject,section,item}}return null}
function weaknessEntries(){return Object.entries(state.user.itemState).filter(([,u])=>u.wrongTokens?.length).map(([id,u])=>({id,u,found:findItem(id)})).filter(x=>x.found)}
function updateWeaknessBadge(){const n=weaknessEntries().length,b=$('#weaknessBadge');if(!b)return;b.textContent=n;b.classList.toggle('hidden',!n)}
function renderWeakness(){const es=weaknessEntries();$('#appMain').innerHTML=`<section class="hero"><div><span class="eyebrow">Weakness Review</span><h1>약점 보충</h1><p>틀린 어절만 다시 모아 복습합니다.</p></div></section>${es.length?`<div class="weakness-grid">${es.map(({id,u,found})=>`<article class="card weak-card"><div><span class="weak-meta">${esc(found.subject.name)} · ${esc(found.section.name)}</span><h3>${esc(found.item.title||'교육과정 원문')}</h3><p>남은 약점 <strong>${u.wrongTokens.length}</strong>개 · 누적 오답 ${u.wrongCount||0}회</p></div><div class="weak-actions"><button class="ghost-btn" data-weak-mask="${id}">가리기 복습</button><button class="primary-btn" data-weak-type="${id}">타이핑 재도전</button></div></article>`).join('')}</div>`:'<div class="card empty-state"><h2>현재 약점이 없어요 🎉</h2></div>'}`;$$('[data-weak-type]').forEach(b=>b.onclick=()=>openWeakStudy(b.dataset.weakType,'typing'));$$('[data-weak-mask]').forEach(b=>b.onclick=()=>openWeakStudy(b.dataset.weakMask,'mask-study'))}
function openWeakStudy(id,mode){const f=findItem(id);if(!f)return;state.subjectId=f.subject.id;state.sectionId=f.section.id;state.itemId=f.item.id;state.weaknessOnly=true;state.studyMode=mode;state.view='study';render()}
function renderSettings(){$('#subjectSettings').innerHTML=allSubjects().map(s=>`<label class="check-row"><input type="checkbox" value="${esc(s.id)}" ${state.settings.visibleSubjects.includes(s.id)?'checked':''}> ${esc(s.name)}</label>`).join('');$('#areaSettings').innerHTML=allSubjects().map(s=>{const sub=subjectData(s.id),secs=sub?.sections||[],enabled=enabledSectionIds(sub||{id:s.id,sections:[]});return`<div class="area-subject"><div class="area-subject-title">${esc(s.name)}</div>${secs.length?`<div class="area-checks">${secs.map(sec=>`<label class="check-row"><input type="checkbox" data-area-subject="${esc(s.id)}" value="${esc(sec.id)}" ${enabled.includes(sec.id)?'checked':''}> ${esc(sec.name)}</label>`).join('')}</div>`:'<p class="muted small-text">아직 업로드된 영역이 없습니다.</p>'}</div>`}).join('');$$('input[name="gradingMode"]').forEach(r=>r.checked=r.value===state.settings.gradingMode);$('#aiProvider').value=state.settings.aiProvider||'none'}
function importPayload(p){if(!p||!Array.isArray(p.subjects))throw new Error('지원하지 않는 JSON 형식입니다.');p.subjects.forEach(s=>mergeSubject(s,true));localStorage.removeItem(BUNDLE_MARKER_KEY);save()}
$('#homeBtn').onclick=()=>{state.view='home';state.weaknessOnly=false;render()};$('#weaknessBtn').onclick=()=>{state.view='weakness';state.weaknessOnly=false;render()};$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{importPayload(JSON.parse(await f.text()));alert('자료를 추가했습니다.');state.view='reader';render()}catch(err){alert(err.message||'JSON 파일을 읽지 못했습니다.')}e.target.value=''};$('#settingsBtn').onclick=()=>{renderSettings();$('#settingsDialog').showModal()};$('#saveSettingsBtn').onclick=()=>{const checked=$$('#subjectSettings input:checked').map(i=>i.value);state.settings.visibleSubjects=checked.length?checked:['general'];state.settings.studySections={};$$('[data-area-subject]').forEach(i=>{state.settings.studySections[i.dataset.areaSubject]??=[];if(i.checked)state.settings.studySections[i.dataset.areaSubject].push(i.value)});state.settings.gradingMode=$('input[name="gradingMode"]:checked')?.value||'flexible';state.settings.aiProvider=$('#aiProvider').value;save();$('#settingsDialog').close();render()};
(async()=>{await loadBundledData();render()})();