(() => {
  const DATA_KEY='tes_curriculum_v5', USER_KEY='tes_user_v5', SETTINGS_KEY='tes_settings_v5';
  const $=s=>document.querySelector(s);
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const PARTICLES=['으로부터','에서부터','에게서','한테서','께서는','에게는','에서는','으로써','으로서','으로는','로부터','까지는','부터는','한테는','께서','에서','에게','한테','으로','이나마','이나','부터','까지','보다','처럼','마다','조차','마저','와','과','은','는','이','가','을','를','의','에','로','도','만'].sort((a,b)=>b.length-a.length);

  function injectCss(){
    if($('#v65Style')) return;
    const style=document.createElement('style'); style.id='v65Style'; style.textContent=`
      #v65Badge{position:fixed;left:10px;bottom:10px;z-index:9999;font:700 10px/1 system-ui;background:#171a21;color:#fff;padding:5px 7px;border-radius:7px;opacity:.7}
      #v65Dock{position:fixed;right:18px;top:210px;z-index:9998;width:158px;padding:12px;background:rgba(255,255,255,.98);border:1px solid #e7e9ee;border-radius:16px;box-shadow:0 14px 38px rgba(23,26,33,.16);display:grid;gap:7px}
      #v65Dock strong{font-size:12px;color:#737987;padding:3px 5px 6px}#v65Dock button{border:1px solid #e7e9ee;background:#fff;color:#171a21;border-radius:10px;padding:9px 10px;text-align:left;font-size:13px}#v65Dock .complete{background:#171a21;color:#fff}
      .v65-word{display:inline;white-space:nowrap}.v65-tail{display:inline!important;color:#171a21!important;background:transparent!important;padding:0!important;margin:0!important;opacity:.8!important}.token.selected+.v65-tail{color:#171a21!important;background:transparent!important}
      .v65-group{box-shadow:inset 0 -2px 0 rgba(49,94,251,.45)}
      @media(max-width:900px){#v65Dock{left:12px;right:12px;top:auto;bottom:12px;width:auto;display:flex;overflow:auto;padding:9px}#v65Dock strong{display:none}#v65Dock button{white-space:nowrap;flex:0 0 auto;text-align:center}#v65Badge{bottom:70px}}
    `; document.head.append(style);
  }
  function cfg(){const s=read(SETTINGS_KEY,{});return {exclude:s.excludeParticles!==false, gradingMode:s.gradingMode||'flexible'};}
  function tokens(text){return String(text||'').split(/(\s+)/).map((text,index)=>({index,text,isSpace:/^\s+$/.test(text)}));}
  function splitParticle(text){
    if(!cfg().exclude) return {core:String(text),suffix:''};
    const raw=String(text), m=raw.match(/^(.*?)([.,!?;:'"“”‘’()\[\]{}<>]*)$/), body=m?.[1]??raw, punct=m?.[2]??'';
    for(const p of PARTICLES){if(!body.endsWith(p))continue;const core=body.slice(0,-p.length);if(!core)continue;return {core,suffix:p+punct};}
    return {core:body,suffix:punct};
  }
  function current(){
    const meta=$('.study-titlebar .eyebrow')?.textContent||'', title=$('.study-titlebar h2')?.textContent?.trim(), [sn,secname]=meta.split('·').map(x=>x.trim()), data=read(DATA_KEY,{subjects:[]});
    for(const sub of data.subjects||[]) if(sub.name===sn) for(const sec of sub.sections||[]) if(sec.name===secname){const item=(sec.items||[]).find(i=>(i.title||'학습')===title)||sec.items?.[0];if(item)return{sub,sec,item};}
    return null;
  }
  function user(id){const all=read(USER_KEY,{itemState:{},rounds:{}});all.itemState??={};all.rounds??={};all.itemState[id]??={masked:[],wrongTokens:[],wrongCount:0,attempts:0,correct:0};const u=all.itemState[id];u.masked??=[];u.wrongTokens??=[];return{all,u,save:()=>write(USER_KEY,all)};}
  function sameLine(ts,a,b){for(let i=a+1;i<b;i++)if(ts[i]?.isSpace&&ts[i].text.includes('\n'))return false;return true;}
  function groups(ts,masked){const sel=new Set(masked||[]), words=ts.filter(t=>!t.isSpace).map(t=>t.index), out=[];let run=[];const flush=()=>{if(run.length>1)out.push([...run]);run=[];};for(let i=0;i<words.length;i++){const idx=words[i];if(!sel.has(idx)){flush();continue;}if(!run.length){run=[idx];continue;}const prev=run.at(-1);if(words[i-1]===prev&&sameLine(ts,prev,idx))run.push(idx);else{flush();run=[idx];}}flush();return out;}
  function editorHtml(item,u){const ts=tokens(item.originalText), gs=groups(ts,u.masked);return ts.map(t=>{if(t.isSpace)return esc(t.text);const p=splitParticle(t.text),selected=u.masked.includes(t.index),grouped=gs.some(g=>g.includes(t.index));return `<span class="v65-word"><span class="token selectable${selected?' selected':''}${grouped?' v65-group':''}" data-v65-token="${t.index}">${esc(p.core)}</span>${p.suffix?`<span class="v65-tail">${esc(p.suffix)}</span>`:''}</span>`;}).join('');}
  function setupEditor(box){if(box.dataset.v65)return;const c=current();if(!c)return;box.dataset.v65='1';const st=user(c.item.id),u=st.u,draw=()=>box.innerHTML=editorHtml(c.item,u);draw();box.onclick=e=>{const el=e.target.closest('[data-v65-token]');if(!el)return;e.preventDefault();e.stopPropagation();const idx=Number(el.dataset.v65Token);u.masked=u.masked.includes(idx)?u.masked.filter(x=>x!==idx):[...u.masked,idx].sort((a,b)=>a-b);st.save();draw();};}
  function build(item,u,typing){const ts=tokens(item.originalText),set=new Set(u.masked),gs=groups(ts,u.masked),first=new Map(gs.map(g=>[g[0],g])),covered=new Set(gs.flatMap(g=>{const a=g[0],b=g.at(-1);return Array.from({length:b-a+1},(_,k)=>a+k);}));let out='';for(let i=0;i<ts.length;i++){const t=ts[i],g=first.get(i);if(g){const a=g[0],b=g.at(-1),parts=ts.slice(a,b+1).map(x=>x.text),last=splitParticle(ts[b].text);if(cfg().exclude)parts[parts.length-1]=last.core;const expected=parts.join(''),suffix=cfg().exclude?last.suffix:'',w=Math.max(120,Math.min(500,expected.length*19+36));out+=typing?`<input class="inline-answer" data-v65-idx="${g.join(',')}" data-v65-exp="${esc(expected)}" style="width:${w}px" autocomplete="off">${suffix?`<span class="v65-tail">${esc(suffix)}</span>`:''}`:`<span class="token masked" data-v65-reveal>${esc(expected)}</span>${suffix?`<span class="v65-tail">${esc(suffix)}</span>`:''}`;i=b;continue;}if(covered.has(i))continue;if(t.isSpace){out+=esc(t.text);continue;}if(!set.has(i)){out+=`<span>${esc(t.text)}</span>`;continue;}const p=splitParticle(t.text),w=Math.max(76,Math.min(280,p.core.length*22+30));out+=typing?`<input class="inline-answer" data-v65-idx="${i}" data-v65-exp="${esc(p.core)}" style="width:${w}px" autocomplete="off">${p.suffix?`<span class="v65-tail">${esc(p.suffix)}</span>`:''}`:`<span class="token masked" data-v65-reveal>${esc(p.core)}</span>${p.suffix?`<span class="v65-tail">${esc(p.suffix)}</span>`:''}`;}return out;}
  function setupMask(box){if(box.dataset.v65)return;const c=current();if(!c)return;const st=user(c.item.id);if(!st.u.masked.length)return;box.dataset.v65='1';box.innerHTML=build(c.item,st.u,false);box.querySelectorAll('[data-v65-reveal]').forEach(el=>el.onclick=()=>el.classList.toggle('revealed'));}
  function norm(v){return String(v||'').toLowerCase().replace(/[\s.,!?;:'"“”‘’·⋅()\[\]{}<>/\\\-_~`]+/g,'');}
  function setupTyping(box){if(box.dataset.v65)return;const c=current();if(!c)return;const st=user(c.item.id),u=st.u;if(!u.masked.length)return;box.dataset.v65='1';box.innerHTML=build(c.item,u,true);const inputs=[...box.querySelectorAll('.inline-answer')];const check=input=>{if(!input.value.trim())return;const exp=input.dataset.v65Exp||'',ids=(input.dataset.v65Idx||'').split(',').map(Number),mode=cfg().gradingMode,ok=mode==='strict'?input.value.trim()===exp.trim():mode==='self'?null:norm(input.value)===norm(exp);input.classList.remove('input-correct','input-wrong','input-self');if(ok===null)input.classList.add('input-self');else if(ok){input.classList.add('input-correct');u.wrongTokens=u.wrongTokens.filter(x=>!ids.includes(x));}else{input.classList.add('input-wrong');ids.forEach(i=>{if(!u.wrongTokens.includes(i))u.wrongTokens.push(i);});input.title=`정답: ${exp}`;}st.save();};inputs.forEach((input,i)=>{input.onblur=()=>check(input);input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();check(input);inputs[i+1]?.focus();}}});}
  function ensureBadge(){if($('#v65Badge'))return;const b=document.createElement('div');b.id='v65Badge';b.textContent='Study v6.5';document.body.append(b);}
  function ensureDock(){const card=$('.study-card');if(!card){$('#v65Dock')?.remove();return;}if($('#v65Dock'))return;const d=document.createElement('aside');d.id='v65Dock';d.innerHTML='<strong>학습 도구</strong><button data-mode-go="mask-edit">가리기 설정</button><button data-mode-go="mask-study">가리기 학습</button><button data-mode-go="typing">타이핑</button><button data-temp>임시 저장</button><button class="complete" data-complete>학습 완료</button>';document.body.append(d);d.querySelectorAll('[data-mode-go]').forEach(b=>b.onclick=()=>document.querySelector(`[data-mode="${b.dataset.modeGo}"]`)?.click());d.querySelector('[data-temp]').onclick=()=>{const c=current();if(c)user(c.item.id).save();alert('임시 저장했어요.');};d.querySelector('[data-complete]').onclick=()=>$('#doneStudyBtn')?.click()||$('#completeItemBtn')?.click();}
  function syncSetting(){const box=$('#particleSelectable');if(!box)return;const s=read(SETTINGS_KEY,{});box.checked=s.excludeParticles!==false;}
  document.addEventListener('change',e=>{if(e.target?.id==='particleSelectable'){const s=read(SETTINGS_KEY,{});s.excludeParticles=e.target.checked;write(SETTINGS_KEY,s);}},true);
  document.addEventListener('click',e=>{if(e.target.closest('#settingsBtn'))setTimeout(syncSetting,0);if(e.target.closest('#saveSettingsBtn')){const checked=$('#particleSelectable')?.checked!==false;setTimeout(()=>{const s=read(SETTINGS_KEY,{});s.excludeParticles=checked;write(SETTINGS_KEY,s);},50);}},true);
  function enhance(){injectCss();ensureBadge();syncSetting();ensureDock();const e=$('.token-editor');if(e)setupEditor(e);const m=$('.mask-study');if(m)setupMask(m);const t=$('.typing-inline');if(t)setupTyping(t);}
  new MutationObserver(enhance).observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
})();