(() => {
  'use strict';
  const DATA_KEY='tes_curriculum_v5', USER_KEY='tes_user_v5', SETTINGS_KEY='tes_settings_v5';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??structuredClone(f)}catch{return structuredClone(f)}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[c]));
  let queued=false;

  function css(){
    if($('#v7Style')) return;
    const st=document.createElement('style'); st.id='v7Style'; st.textContent=`
      #v7Badge{position:fixed;left:10px;bottom:10px;z-index:9999;font:700 10px/1 system-ui;background:#171a21;color:#fff;padding:5px 7px;border-radius:7px;opacity:.52}
      .reader .reader-actions,.study-titlebar .mode-switch,.study-card>.study-footer{display:none!important}
      .v7-word{display:inline-flex;align-items:baseline;white-space:nowrap}.v7-core{margin:2px 1px!important}.v7-tail{display:inline;color:var(--text);opacity:.8;margin-right:2px}.v7-core.selected+.v7-tail{background:transparent!important;color:var(--text)!important}
      .v7-group{box-shadow:inset 0 -2px 0 rgba(49,94,251,.48)}
      #v7Dock{position:fixed;z-index:95;width:184px;padding:10px;background:rgba(255,255,255,.98);border:1px solid var(--line);border-radius:15px;box-shadow:0 12px 34px rgba(23,26,33,.13);backdrop-filter:blur(12px);display:grid;gap:7px;transition:.18s}
      #v7Dock.collapsed{width:46px;padding:8px 6px}#v7Dock.collapsed .v7-body,#v7Dock.collapsed .v7-title{display:none}
      .v7-head{display:flex;align-items:center;justify-content:space-between;gap:6px}.v7-title{font-size:12px;color:var(--muted);font-weight:800;padding-left:4px}.v7-collapse{border:1px solid var(--line);background:#fff;border-radius:9px;padding:5px 8px}.v7-body{display:grid;gap:6px}.v7-body button{border:1px solid var(--line);background:#fff;color:var(--text);border-radius:10px;padding:9px 10px;text-align:left;font-size:13px}.v7-body button.active{background:var(--primary-soft);color:var(--primary);border-color:#dfe5ff;font-weight:700}.v7-body button.complete{background:#171a21;color:#fff;border-color:#171a21}.v7-body hr{width:100%;border:0;border-top:1px solid var(--line);margin:2px 0}.v7-save{font-size:10px;color:var(--muted);padding:1px 4px 3px}
      .section-bar .v7-done-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#22c55e;margin-left:7px;box-shadow:0 0 0 3px rgba(34,197,94,.12)}
      .v7-table-wrap{overflow-x:auto;margin:22px 0}.v7-caption{font-size:13px;font-weight:750;margin:0 0 8px;color:var(--text)}.v7-table{border-collapse:separate;border-spacing:0;width:100%;min-width:640px;border:1px solid var(--line);border-radius:12px;overflow:hidden;background:#fff}.v7-table th,.v7-table td{border-right:1px solid var(--line);border-bottom:1px solid var(--line);padding:12px 13px;vertical-align:top;line-height:1.65;white-space:pre-line}.v7-table th{background:#f6f7f9;font-weight:800;text-align:center}.v7-table tr:last-child>*{border-bottom:0}.v7-table tr>*:last-child{border-right:0}
      .v7-toast{position:fixed;left:50%;bottom:28px;transform:translate(-50%,14px);z-index:120;background:#171a21;color:#fff;padding:10px 14px;border-radius:10px;opacity:0;pointer-events:none;transition:.18s;font-size:13px}.v7-toast.show{opacity:1;transform:translate(-50%,0)}
      @media(max-width:900px){#v7Dock{left:12px!important;right:12px!important;top:auto!important;bottom:12px!important;width:auto!important;display:flex;align-items:center;padding:8px}.v7-head{flex:0 0 auto}.v7-title{display:none}.v7-body{display:flex;overflow-x:auto}.v7-body hr,.v7-save{display:none}.v7-body button{white-space:nowrap;flex:0 0 auto;text-align:center}.reader,.study-card{padding-bottom:96px}#v7Dock.collapsed{left:auto!important;right:12px!important;width:46px!important}.v7-word{white-space:normal}}
    `; document.head.append(st);
  }
  function data(){return read(DATA_KEY,{subjects:[]})}
  function settings(){return read(SETTINGS_KEY,{})}
  function current(){
    const d=data();
    const studyMeta=$('.study-titlebar .eyebrow')?.textContent||'';
    const studyTitle=$('.study-titlebar h2')?.textContent?.trim();
    if(studyMeta&&studyTitle){const [sn,secname]=studyMeta.split('·').map(x=>x.trim());for(const sub of d.subjects||[])if(sub.name===sn)for(const sec of sub.sections||[])if(sec.name===secname){const item=(sec.items||[]).find(i=>(i.title||'학습')===studyTitle)||sec.items?.[0];if(item)return{sub,sec,item,view:'study'};}}
    const bc=$('.reader .breadcrumb')?.textContent||''; const title=$('.reader .reader-heading h1')?.textContent?.trim();
    if(bc&&title){const [sn,secname]=bc.split('/').map(x=>x.trim());for(const sub of d.subjects||[])if(sub.name===sn)for(const sec of sub.sections||[])if(sec.name===secname){const item=(sec.items||[]).find(i=>(i.title||'교육과정 원문')===title)||sec.items?.[0];if(item)return{sub,sec,item,view:'reader'};}}
    return null;
  }
  function units(item){
    if(Array.isArray(item?.studyUnits)&&item.studyUnits.length)return item.studyUnits;
    return String(item?.originalText||'').split(/(\s+)/).reduce((a,x,i)=>{if(!x||/^\s+$/.test(x))return a; a.push({id:`legacy-${i}`,surface:x,core:x,particle:'',punctuation:'',leadingSpace:' ',semanticUnit:'legacy',legacyTokenIndex:i});return a;},[]);
  }
  function stateFor(item){const all=read(USER_KEY,{itemState:{},rounds:{},drafts:{}});all.itemState??={};all.rounds??={};all.drafts??={};all.itemState[item.id]??={masked:[],wrongTokens:[],wrongCount:0,attempts:0,correct:0};const u=all.itemState[item.id];u.masked??=[];u.wrongTokens??=[];return{all,u,save:()=>write(USER_KEY,all)};}
  function selectedOrdinals(item,u){
    const us=units(item),legacy=new Map(us.map((x,i)=>[x.legacyTokenIndex,i]));
    return [...new Set((u.masked||[]).map(v=>legacy.has(v)?legacy.get(v):(Number.isInteger(v)&&v<us.length?v:null)).filter(v=>v!==null))].sort((a,b)=>a-b);
  }
  function saveOrdinals(item,u,ords){const us=units(item);u.masked=ords.map(i=>us[i]?.legacyTokenIndex??i).filter(v=>v!==undefined);}
  function groupRuns(item,u){const us=units(item),sel=new Set(selectedOrdinals(item,u)),runs=[];let run=[];const flush=()=>{if(run.length>1)runs.push([...run]);run=[]};for(let i=0;i<us.length;i++){if(!sel.has(i)){flush();continue}if(!run.length){run=[i];continue}const p=run.at(-1);if(i===p+1&&us[i].semanticUnit===us[p].semanticUnit)run.push(i);else{flush();run=[i]}}flush();return runs;}
  function includeParticles(){return settings().excludeParticles===false}
  function visibleParts(u){return includeParticles()?{core:u.surface,tail:''}:{core:u.core||u.surface,tail:`${u.particle||''}${u.punctuation||''}`}}
  function editorHtml(item,u){const us=units(item),sel=new Set(selectedOrdinals(item,u)),runs=groupRuns(item,u);return us.map((x,i)=>{const p=visibleParts(x),grp=runs.some(r=>r.includes(i));return `${esc(x.leadingSpace||'')}<span class="v7-word"><span class="token selectable v7-core${sel.has(i)?' selected':''}${grp?' v7-group':''}" data-v7-unit="${i}">${esc(p.core)}</span>${p.tail?`<span class="v7-tail">${esc(p.tail)}</span>`:''}</span>`}).join('')+esc(us.at(-1)?.trailingSpace||'')}
  function setupEditor(box){if(box.dataset.v7==='1')return;const c=current();if(!c)return;box.dataset.v7='1';const st=stateFor(c.item),u=st.u,draw=()=>box.innerHTML=editorHtml(c.item,u);draw();box.addEventListener('click',e=>{const el=e.target.closest('[data-v7-unit]');if(!el)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const idx=Number(el.dataset.v7Unit),s=new Set(selectedOrdinals(c.item,u));s.has(idx)?s.delete(idx):s.add(idx);saveOrdinals(c.item,u,[...s].sort((a,b)=>a-b));st.save();draw()},true)}
  function build(item,u,typing){const us=units(item),sel=new Set(selectedOrdinals(item,u)),runs=groupRuns(item,u),first=new Map(runs.map(r=>[r[0],r])),covered=new Set(runs.flat());let out='';for(let i=0;i<us.length;i++){const x=us[i];out+=esc(x.leadingSpace||'');const run=first.get(i);if(run){const parts=run.map(j=>visibleParts(us[j]).core),last=visibleParts(us[run.at(-1)]),exp=parts.join(' '),tail=last.tail,w=Math.max(120,Math.min(520,exp.length*18+38));out+=typing?`<input class="inline-answer" data-v7-idx="${run.join(',')}" data-v7-exp="${esc(exp)}" style="width:${w}px" autocomplete="off">${tail?`<span class="v7-tail">${esc(tail)}</span>`:''}`:`<span class="token masked" data-v7-reveal="${run.join(',')}">${esc(exp)}</span>${tail?`<span class="v7-tail">${esc(tail)}</span>`:''}`;i=run.at(-1);continue}if(covered.has(i))continue;if(!sel.has(i)){out+=esc(x.surface);continue}const p=visibleParts(x),w=Math.max(76,Math.min(300,p.core.length*22+30));out+=typing?`<input class="inline-answer" data-v7-idx="${i}" data-v7-exp="${esc(p.core)}" style="width:${w}px" autocomplete="off">${p.tail?`<span class="v7-tail">${esc(p.tail)}</span>`:''}`:`<span class="token masked" data-v7-reveal="${i}">${esc(p.core)}</span>${p.tail?`<span class="v7-tail">${esc(p.tail)}</span>`:''}`;}out+=esc(us.at(-1)?.trailingSpace||'');return out}
  function setupMask(box){if(box.dataset.v7==='1')return;const c=current();if(!c)return;const st=stateFor(c.item);if(!selectedOrdinals(c.item,st.u).length)return;box.dataset.v7='1';box.innerHTML=build(c.item,st.u,false);const d=st.all.drafts[c.item.id];box.querySelectorAll('[data-v7-reveal]').forEach(el=>{if(d?.revealed?.includes(el.dataset.v7Reveal))el.classList.add('revealed');el.onclick=()=>el.classList.toggle('revealed')})}
  function norm(v){return String(v||'').toLowerCase().replace(/[\s.,!?;:'"“”‘’·⋅()\[\]{}<>/\\\-_~`]+/g,'')}
  function setupTyping(box){if(box.dataset.v7==='1')return;const c=current();if(!c)return;const st=stateFor(c.item),u=st.u;if(!selectedOrdinals(c.item,u).length)return;box.dataset.v7='1';box.innerHTML=build(c.item,u,true);const ins=[...box.querySelectorAll('.inline-answer')],d=st.all.drafts[c.item.id];if(d?.typingValues)ins.forEach(i=>{if(i.dataset.v7Idx in d.typingValues)i.value=d.typingValues[i.dataset.v7Idx]});const check=input=>{if(!input.value.trim())return;const exp=input.dataset.v7Exp||'',ids=(input.dataset.v7Idx||'').split(',').map(Number),mode=settings().gradingMode||'flexible',ok=mode==='strict'?input.value.trim()===exp.trim():mode==='self'?null:norm(input.value)===norm(exp);input.classList.remove('input-correct','input-wrong','input-self');if(ok===null)input.classList.add('input-self');else if(ok){input.classList.add('input-correct');u.wrongTokens=(u.wrongTokens||[]).filter(x=>!ids.includes(x))}else{input.classList.add('input-wrong');ids.forEach(i=>{if(!u.wrongTokens.includes(i))u.wrongTokens.push(i)});input.title=`정답: ${exp}`}st.save()};ins.forEach((input,i)=>{input.onblur=()=>check(input);input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();check(input);ins[i+1]?.focus()}}})}
  function renderTable(block){const occ=new Set(),map=new Map((block.cells||[]).map(c=>[`${c.row}:${c.col}`,c])),widths=block.columnWidths||[];let h='<div class="v7-table-wrap">';if(block.caption)h+=`<div class="v7-caption">${esc(block.caption)}</div>`;h+='<table class="v7-table"><colgroup>'+Array.from({length:block.cols||0},(_,i)=>`<col style="width:${Math.round((widths[i]||1/(block.cols||1))*10000)/100}%">`).join('')+'</colgroup><tbody>';for(let r=0;r<(block.rows||0);r++){h+='<tr>';for(let c=0;c<(block.cols||0);c++){if(occ.has(`${r}:${c}`))continue;const cell=map.get(`${r}:${c}`);if(!cell){h+='<td></td>';continue}for(let rr=r;rr<r+(cell.rowspan||1);rr++)for(let cc=c;cc<c+(cell.colspan||1);cc++)if(rr!==r||cc!==c)occ.add(`${rr}:${cc}`);const tag=cell.header||r<(block.headerRows||0)?'th':'td',txt=(cell.segments||[{text:cell.text||''}]).map(s=>esc(s.text)).join('');h+=`<${tag} rowspan="${cell.rowspan||1}" colspan="${cell.colspan||1}">${txt}</${tag}>`}h+='</tr>'}return h+'</tbody></table></div>'}
  function upgradeTables(){const c=current();if(!c||c.view!=='reader')return;const blocks=(c.item.blocks||[]).filter(b=>b.type==='table'),dom=$$('.reader .table-scroll');if(!blocks.length||!dom.length)return;dom.forEach((el,i)=>{const b=blocks[i];if(!b||b.tableVersion!==7||el.dataset.v7==='1')return;const wrap=document.createElement('div');wrap.innerHTML=renderTable(b);const n=wrap.firstElementChild;n.dataset.v7='1';el.replaceWith(n)})}
  function toast(msg){let t=$('#v7Toast');if(!t){t=document.createElement('div');t.id='v7Toast';t.className='v7-toast';document.body.append(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),1700)}
  function mode(){if($('.reader'))return'reader';return $('.mode-switch [data-mode].active')?.dataset.mode||'mask-edit'}
  function tempSave(){const c=current();if(!c)return;const st=stateFor(c.item),vals={};$$('.typing-inline .inline-answer').forEach(i=>vals[i.dataset.v7Idx||'']=i.value);const rev=$$('.mask-study [data-v7-reveal].revealed').map(x=>x.dataset.v7Reveal);st.all.drafts[c.item.id]={mode:mode(),typingValues:vals,revealed:rev,scrollY:scrollY,savedAt:Date.now()};st.save();updateSave();toast('현재 학습 상태를 임시 저장했어요.')}
  function enabledSections(sub){const prefs=settings().sectionPrefs?.[sub.id]||{};return(sub.sections||[]).filter(sec=>prefs[sec.id]?.study!==false)}
  function complete(){const c=current();if(!c)return;const st=stateFor(c.item),r=st.all.rounds[c.sub.id]??={count:0,completed:[]};if(!r.completed.includes(c.item.id))r.completed.push(c.item.id);const all=enabledSections(c.sub).flatMap(s=>(s.items||[]).map(i=>i.id));if(all.length&&all.every(id=>r.completed.includes(id))){r.count=(r.count||0)+1;r.completed=[];toast(`${c.sub.name} ${r.count}회독 완료!`)}else toast('학습 완료로 저장했어요.');st.save();dots()}
  function dots(){const c=current();if(!c)return;const done=read(USER_KEY,{rounds:{}}).rounds?.[c.sub.id]?.completed||[];$$('#sectionBar [data-section]').forEach(b=>{const sec=(c.sub.sections||[]).find(s=>s.id===b.dataset.section),ids=(sec?.items||[]).map(i=>i.id),ok=ids.length&&ids.every(id=>done.includes(id)),dot=b.querySelector('.v7-done-dot');if(ok&&!dot){const x=document.createElement('span');x.className='v7-done-dot';b.append(x)}else if(!ok&&dot)dot.remove()})}
  function go(m){if(m==='reader'){if($('.study-card'))$('#backReaderBtn')?.click();return}if($('.reader')){if(m==='mask-edit')$('#maskStartBtn')?.click();else if(m==='typing')$('#typingStartBtn')?.click();else if(m==='mask-study'){$('#maskStartBtn')?.click();setTimeout(()=>document.querySelector('[data-mode="mask-study"]')?.click(),50)}return}document.querySelector(`[data-mode="${m}"]`)?.click()}
  function ensureDock(){const c=current();if(!c){$('#v7Dock')?.remove();return}let d=$('#v7Dock');if(!d){d=document.createElement('aside');d.id='v7Dock';d.innerHTML='<div class="v7-head"><span class="v7-title">학습 도구</span><button class="v7-collapse">‹</button></div><div class="v7-body"><button data-v7-mode="reader">원문</button><button data-v7-mode="mask-edit">가리기 설정</button><button data-v7-mode="mask-study">가리기 학습</button><button data-v7-mode="typing">타이핑</button><hr><button data-v7-temp>임시 저장</button><div id="v7Save" class="v7-save"></div><button class="complete" data-v7-complete>학습 완료</button></div>';document.body.append(d);d.querySelector('.v7-collapse').onclick=()=>{const s=settings();s.studyDockCollapsed=!d.classList.contains('collapsed');write(SETTINGS_KEY,s);dockState();positionDock()};d.querySelectorAll('[data-v7-mode]').forEach(b=>b.onclick=()=>go(b.dataset.v7Mode));d.querySelector('[data-v7-temp]').onclick=tempSave;d.querySelector('[data-v7-complete]').onclick=complete}dockState();$$('#v7Dock [data-v7-mode]').forEach(b=>b.classList.toggle('active',b.dataset.v7Mode===mode()));updateSave();positionDock()}
  function dockState(){const d=$('#v7Dock');if(!d)return;const col=settings().studyDockCollapsed===true;d.classList.toggle('collapsed',col);d.querySelector('.v7-collapse').textContent=col?'›':'‹'}
  function positionDock(){const d=$('#v7Dock'),card=$('.reader')||$('.study-card');if(!d||!card||innerWidth<=900)return;const r=card.getBoundingClientRect(),w=d.classList.contains('collapsed')?46:184;let left=r.right+14;if(left+w>innerWidth-12)left=Math.max(12,r.right-w-12);d.style.left=`${Math.round(left)}px`;d.style.right='auto';d.style.top=`${Math.max(196,Math.round(r.top))}px`}
  function updateSave(){const c=current(),el=$('#v7Save');if(!c||!el)return;const d=read(USER_KEY,{drafts:{}}).drafts?.[c.item.id];el.textContent=d?.savedAt?`임시 저장 ${new Date(d.savedAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`:'아직 임시 저장 없음'}
  function seedCreative(){const d=data(),has=(d.subjects||[]).some(s=>s.id==='creative');if(!has)return;const s=settings();s.visibleSubjects??=[];if(!s.visibleSubjects.includes('creative')){const gi=s.visibleSubjects.indexOf('general');s.visibleSubjects.splice(gi>=0?gi+1:0,0,'creative');write(SETTINGS_KEY,s)}}
  function enhance(){css();if(!$('#v7Badge')){const b=document.createElement('div');b.id='v7Badge';b.textContent='Study v7';document.body.append(b)}seedCreative();ensureDock();dots();upgradeTables();const e=$('.token-editor');if(e)setupEditor(e);const m=$('.mask-study');if(m)setupMask(m);const t=$('.typing-inline');if(t)setupTyping(t)}
  function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance()})}
  new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});addEventListener('resize',positionDock);addEventListener('scroll',positionDock,{passive:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
})();
