(() => {
'use strict';
const DATA='tes_curriculum_v5', USER='tes_user_v5', SETTINGS='tes_settings_v5', CTX='tes_v75_context';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??structuredClone(f)}catch{return structuredClone(f)}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let queued=false,currentMode='reader';
function css(){if($('#v75style'))return;const s=document.createElement('style');s.id='v75style';s.textContent=`
#v75badge{position:fixed;left:10px;bottom:10px;z-index:9999;font:700 10px/1 system-ui;background:#171a21;color:#fff;padding:5px 7px;border-radius:7px;opacity:.6}.reader .reader-actions,.study-titlebar .mode-switch,.study-card>.study-footer{display:none!important}
#v75dock{position:fixed;z-index:120;width:184px;padding:10px;background:rgba(255,255,255,.98);border:1px solid var(--line);border-radius:15px;box-shadow:0 12px 34px rgba(23,26,33,.14);display:grid;gap:7px;transition:.18s}#v75dock.collapsed{width:46px;padding:8px 6px}#v75dock.collapsed .v75body,#v75dock.collapsed .v75title{display:none}.v75head{display:flex;align-items:center;justify-content:space-between;gap:6px}.v75title{font-size:12px;color:var(--muted);font-weight:800;padding-left:4px}.v75collapse{border:1px solid var(--line);background:#fff;border-radius:9px;padding:5px 8px;cursor:pointer}.v75body{display:grid;gap:6px}.v75body button{border:1px solid var(--line);background:#fff;color:var(--text);border-radius:10px;padding:9px 10px;text-align:left;font-size:13px;cursor:pointer}.v75body button.active{background:var(--primary-soft);color:var(--primary);border-color:#dfe5ff;font-weight:700}.v75body button.complete{background:#171a21;color:#fff;border-color:#171a21}.v75body hr{width:100%;border:0;border-top:1px solid var(--line);margin:2px 0}.v75save{font-size:10px;color:var(--muted);padding:1px 4px 3px}
.v75word{display:inline-flex;align-items:baseline;white-space:nowrap}.v75core{margin:2px 1px!important}.v75tail{display:inline!important;background:transparent!important;color:var(--text)!important;opacity:.84;margin-right:2px}.v75group{box-shadow:inset 0 -2px 0 rgba(49,94,251,.55)}.v75helper{font-size:13px;color:var(--muted);padding:11px 13px;background:#f7f8fa;border-radius:10px;margin-bottom:14px}.v75need{padding:16px;border:1px solid #f2c94c;background:#fffaf0;border-radius:12px;line-height:1.55}
.mask-study [data-v75-reveal].v75correct{color:var(--text)!important;background:transparent!important;border:2px solid #22c55e!important;box-shadow:0 0 0 3px rgba(34,197,94,.10)!important;padding:2px 5px!important}.mask-study [data-v75-reveal].v75wrong{color:var(--text)!important;background:transparent!important;border:2px solid #ef4444!important;box-shadow:0 0 0 3px rgba(239,68,68,.10)!important;padding:2px 5px!important}
.section-bar .v75dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#22c55e;margin-left:7px;box-shadow:0 0 0 3px rgba(34,197,94,.12)}.v75toast{position:fixed;left:50%;bottom:28px;transform:translate(-50%,14px);z-index:140;background:#171a21;color:#fff;padding:10px 14px;border-radius:10px;opacity:0;pointer-events:none;transition:.18s}.v75toast.show{opacity:1;transform:translate(-50%,0)}
@media(max-width:900px){#v75dock{left:12px!important;right:12px!important;top:auto!important;bottom:12px!important;width:auto!important;display:flex;align-items:center;padding:8px}.v75head{flex:0 0 auto}.v75title{display:none}.v75body{display:flex;overflow-x:auto}.v75body hr,.v75save{display:none}.v75body button{white-space:nowrap;flex:0 0 auto;text-align:center}.reader,.study-card{padding-bottom:96px}#v75dock.collapsed{left:auto!important;right:12px!important;width:46px!important}.v75word{white-space:normal}}
`;document.head.append(s)}
function data(){return read(DATA,{subjects:[]})} function cfg(){return read(SETTINGS,{})}
function findByIds(ids){const d=data(),sub=(d.subjects||[]).find(x=>x.id===ids?.subjectId),sec=(sub?.sections||[]).find(x=>x.id===ids?.sectionId),item=(sec?.items||[]).find(x=>x.id===ids?.itemId);return item?{sub,sec,item}:null}
function context(){const d=data();const bc=$('.reader .breadcrumb')?.textContent||'',rt=$('.reader .reader-heading h1')?.textContent?.trim();if(bc&&rt){const [sn,secn]=bc.split('/').map(x=>x.trim());for(const sub of d.subjects||[])if(sub.name===sn)for(const sec of sub.sections||[])if(sec.name===secn){const item=(sec.items||[]).find(i=>(i.title||'교육과정 원문')===rt)||sec.items?.[0];if(item){const c={sub,sec,item,view:'reader'};sessionStorage.setItem(CTX,JSON.stringify({subjectId:sub.id,sectionId:sec.id,itemId:item.id}));return c}}}const sm=$('.study-titlebar .eyebrow')?.textContent||'',st=$('.study-titlebar h2')?.textContent?.trim();if(sm&&st){const [sn,secn]=sm.split('·').map(x=>x.trim());for(const sub of d.subjects||[])if(sub.name===sn)for(const sec of sub.sections||[])if(sec.name===secn){const item=(sec.items||[]).find(i=>(i.title||'학습')===st)||sec.items?.[0];if(item){const c={sub,sec,item,view:'study'};sessionStorage.setItem(CTX,JSON.stringify({subjectId:sub.id,sectionId:sec.id,itemId:item.id}));return c}}}try{const c=findByIds(JSON.parse(sessionStorage.getItem(CTX)||'null'));if(c)return{...c,view:$('.study-card')?'study':'reader'}}catch{}return null}
function units(item){return Array.isArray(item?.studyUnits)&&item.studyUnits.length?item.studyUnits:null}
function stateFor(item){const all=read(USER,{itemState:{},rounds:{},drafts:{}});all.itemState??={};all.rounds??={};all.drafts??={};all.itemState[item.id]??={masked:[],maskedUnits:[],wrongTokens:[],wrongCount:0,attempts:0,correct:0};const u=all.itemState[item.id];u.masked??=[];u.maskedUnits??=[];u.wrongTokens??=[];all.drafts[item.id]??={};const us=units(item);if(us&&u.maskedUnits.length===0&&u.masked.length){const legacy=new Map(us.map((x,i)=>[x.legacyTokenIndex,i]));u.maskedUnits=[...new Set(u.masked.map(v=>legacy.has(v)?legacy.get(v):(Number.isInteger(v)&&v<us.length?v:null)).filter(v=>v!==null))].sort((a,b)=>a-b)}return{all,u,draft:all.drafts[item.id],save:()=>write(USER,all)}}
function selected(item,u){const us=units(item);return us?[...new Set((u.maskedUnits||[]).filter(i=>Number.isInteger(i)&&i>=0&&i<us.length))].sort((a,b)=>a-b):[]}
function setSelected(item,u,arr){const us=units(item);u.maskedUnits=[...new Set(arr)].sort((a,b)=>a-b);u.masked=u.maskedUnits.map(i=>us[i]?.legacyTokenIndex??i)}
function parts(x){return cfg().excludeParticles===false?{core:x.surface,tail:''}:{core:x.core||x.surface,tail:`${x.particle||''}${x.punctuation||''}`}}
function runs(item,u){const us=units(item),s=new Set(selected(item,u)),out=[];let run=[];const flush=()=>{if(run.length>1)out.push([...run]);run=[]};for(let i=0;i<us.length;i++){if(!s.has(i)){flush();continue}if(!run.length){run=[i];continue}const p=run.at(-1);if(i===p+1&&us[i].semanticUnit===us[p].semanticUnit)run.push(i);else{flush();run=[i]}}flush();return out}
function groupExpected(us,r){if(cfg().excludeParticles===false)return r.map(i=>us[i].surface).join(' ');return r.map((i,n)=>n===r.length-1?(us[i].core||us[i].surface):us[i].surface).join(' ')}
function need(){return '<div class="v75need"><strong>이 항목에는 v7.5 학습 단위가 없습니다.</strong><br>설정에서 최신 본문 JSON을 다시 일괄 업로드해 주세요.</div>'}
function editorHTML(item,u){const us=units(item),sel=new Set(selected(item,u)),gs=runs(item,u);return us.map((x,i)=>{const p=parts(x),g=gs.some(r=>r.includes(i));return `${esc(x.leadingSpace||'')}<span class="v75word"><span class="token selectable v75core${sel.has(i)?' selected':''}${g?' v75group':''}" data-v75-unit="${i}">${esc(p.core)}</span>${p.tail?`<span class="v75tail">${esc(p.tail)}</span>`:''}</span>`}).join('')+esc(us.at(-1)?.trailingSpace||'')}
function build(item,u,typing){const us=units(item),sel=new Set(selected(item,u)),gs=runs(item,u),first=new Map(gs.map(r=>[r[0],r])),covered=new Set(gs.flat());let out='';for(let i=0;i<us.length;i++){const x=us[i];out+=esc(x.leadingSpace||'');const r=first.get(i);if(r){const exp=groupExpected(us,r),last=parts(us[r.at(-1)]),w=Math.max(120,Math.min(560,exp.length*18+38));out+=typing?`<input class="inline-answer" data-v75-idx="${r.join(',')}" data-v75-exp="${esc(exp)}" style="width:${w}px" autocomplete="off">${last.tail?`<span class="v75tail">${esc(last.tail)}</span>`:''}`:`<span class="token masked" data-v75-reveal="${r.join(',')}">${esc(exp)}</span>${last.tail?`<span class="v75tail">${esc(last.tail)}</span>`:''}`;i=r.at(-1);continue}if(covered.has(i))continue;if(!sel.has(i)){out+=esc(x.surface);continue}const p=parts(x),w=Math.max(76,Math.min(320,p.core.length*22+30));out+=typing?`<input class="inline-answer" data-v75-idx="${i}" data-v75-exp="${esc(p.core)}" style="width:${w}px" autocomplete="off">${p.tail?`<span class="v75tail">${esc(p.tail)}</span>`:''}`:`<span class="token masked" data-v75-reveal="${i}">${esc(p.core)}</span>${p.tail?`<span class="v75tail">${esc(p.tail)}</span>`:''}`;}out+=esc(us.at(-1)?.trailingSpace||'');return out}
function renderEditor(c){const box=$('#studyContent');if(!box)return;const st=stateFor(c.item);if(!units(c.item)){box.innerHTML=need();return}box.innerHTML=`<div class="v75helper">암기할 어절을 터치하세요. 같은 의미 단위에서 <strong>연속 선택한 어절은 가리기/타이핑에서 빈칸 하나로 연결</strong>됩니다.</div><div class="token-editor">${editorHTML(c.item,st.u)}</div>`;box.querySelector('.token-editor').onclick=e=>{const el=e.target.closest('[data-v75-unit]');if(!el)return;e.preventDefault();const live=stateFor(c.item),i=Number(el.dataset.v75Unit),s=new Set(selected(c.item,live.u));s.has(i)?s.delete(i):s.add(i);setSelected(c.item,live.u,[...s]);live.save();renderEditor(c)}}
function legacyIds(item,ids){const us=units(item)||[];return ids.map(i=>us[i]?.legacyTokenIndex??i)}
function applyFeedback(el,state){el.classList.remove('revealed','v75correct','v75wrong');if(state==='correct')el.classList.add('revealed','v75correct');if(state==='wrong')el.classList.add('revealed','v75wrong')}
function renderMask(c){const box=$('#studyContent');if(!box)return;const st=stateFor(c.item);if(!units(c.item)){box.innerHTML=need();return}if(!selected(c.item,st.u).length){box.innerHTML='<div class="v75need"><strong>가리기 설정이 아직 없습니다.</strong><br>사이드바에서 가리기 설정으로 이동해 어절을 선택해 주세요.</div>';return}box.innerHTML=`<div class="v75helper">빈칸을 <strong>한 번 터치하면 정답(초록)</strong>, 한 번 더 터치하면 <strong>오답(빨강)</strong>, 세 번째 터치하면 다시 가립니다.</div><div class="mask-study">${build(c.item,st.u,false)}</div>`;st.draft.maskFeedback??={};box.querySelectorAll('[data-v75-reveal]').forEach(el=>{const key=el.dataset.v75Reveal;applyFeedback(el,st.draft.maskFeedback[key]||'hidden');el.onclick=e=>{e.preventDefault();const live=stateFor(c.item);live.draft.maskFeedback??={};const now=live.draft.maskFeedback[key]||'hidden',next=now==='hidden'?'correct':now==='correct'?'wrong':'hidden',ids=key.split(',').map(Number),lids=legacyIds(c.item,ids);live.draft.maskFeedback[key]=next;if(next==='correct')live.u.wrongTokens=(live.u.wrongTokens||[]).filter(x=>!lids.includes(Number(x)));if(next==='wrong'){lids.forEach(i=>{if(!live.u.wrongTokens.some(x=>Number(x)===i))live.u.wrongTokens.push(i)});live.u.wrongCount=(live.u.wrongCount||0)+1}live.save();applyFeedback(el,next)}})}
function norm(v){return String(v||'').toLowerCase().replace(/[\s.,!?;:'"“”‘’·⋅()\[\]{}<>/\\\-_~`]+/g,'')}
function renderTyping(c){const box=$('#studyContent');if(!box)return;const st=stateFor(c.item);if(!units(c.item)){box.innerHTML=need();return}if(!selected(c.item,st.u).length){box.innerHTML='<div class="v75need"><strong>타이핑할 빈칸이 없습니다.</strong><br>먼저 가리기 설정에서 어절을 선택해 주세요.</div>';return}box.innerHTML=`<div class="v75helper">연결된 빈칸은 한 입력칸으로 답하세요. Enter 또는 다음 칸으로 이동하면 채점됩니다.</div><div class="typing-inline">${build(c.item,st.u,true)}</div><div id="v75typingResult"></div>`;const ins=[...box.querySelectorAll('.inline-answer')];if(st.draft.typingValues)ins.forEach(i=>{if(i.dataset.v75Idx in st.draft.typingValues)i.value=st.draft.typingValues[i.dataset.v75Idx]});const check=input=>{if(!input.value.trim())return;const live=stateFor(c.item),exp=input.dataset.v75Exp||'',ids=(input.dataset.v75Idx||'').split(',').map(Number),lids=legacyIds(c.item,ids),m=cfg().gradingMode||'flexible',ok=m==='strict'?input.value.trim()===exp.trim():m==='self'?null:norm(input.value)===norm(exp);input.classList.remove('input-correct','input-wrong','input-self');if(ok===null)input.classList.add('input-self');else if(ok){input.classList.add('input-correct');live.u.wrongTokens=(live.u.wrongTokens||[]).filter(x=>!lids.includes(Number(x)))}else{input.classList.add('input-wrong');lids.forEach(i=>{if(!live.u.wrongTokens.some(x=>Number(x)===i))live.u.wrongTokens.push(i)});input.title=`정답: ${exp}`}live.save()};ins.forEach((i,n)=>{i.oninput=()=>{const live=stateFor(c.item);live.draft.typingValues??={};live.draft.typingValues[i.dataset.v75Idx]=i.value;live.save()};i.onblur=()=>check(i);i.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();check(i);ins[n+1]?.focus()}}})}
function renderMode(m){const c=context();if(!c||!$('.study-card'))return;currentMode=m;if(m==='mask-edit')renderEditor(c);else if(m==='mask-study')renderMask(c);else renderTyping(c);updateDock()}
function waitStudy(m){let n=0;const t=setInterval(()=>{n++;if($('.study-card')){clearInterval(t);renderMode(m)}else if(n>40){clearInterval(t);toast('학습 화면을 열지 못했습니다. 페이지를 새로고침해 주세요.')}},25)}
function enter(m){const c=context();if(!c)return;if($('.reader')){sessionStorage.setItem(CTX,JSON.stringify({subjectId:c.sub.id,sectionId:c.sec.id,itemId:c.item.id}));if(m==='typing')$('#typingStartBtn')?.click();else $('#maskStartBtn')?.click();waitStudy(m);return}if($('.study-card'))renderMode(m)}
function goReader(){if($('.study-card'))$('#backReaderBtn')?.click()}
function toast(msg){let t=$('#v75toast');if(!t){t=document.createElement('div');t.id='v75toast';t.className='v75toast';document.body.append(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._);t._=setTimeout(()=>t.classList.remove('show'),1700)}
function tempSave(){const c=context();if(!c)return;const st=stateFor(c.item);st.draft.mode=currentMode;st.draft.scrollY=scrollY;st.draft.savedAt=Date.now();st.save();updateSave();toast('현재 학습 상태를 저장했어요.')}
function enabledSections(sub){const p=cfg().sectionPrefs?.[sub.id]||{};return(sub.sections||[]).filter(sec=>p[sec.id]?.study!==false)}
function complete(){const c=context();if(!c)return;const st=stateFor(c.item),r=st.all.rounds[c.sub.id]??={count:0,completed:[]};if(!r.completed.includes(c.item.id))r.completed.push(c.item.id);const all=enabledSections(c.sub).flatMap(s=>(s.items||[]).map(i=>i.id));if(all.length&&all.every(id=>r.completed.includes(id))){r.count=(r.count||0)+1;r.completed=[];toast(`${c.sub.name} ${r.count}회독 완료!`)}else toast('학습 완료로 저장했어요.');st.save();dots()}
function dots(){const c=context();if(!c)return;const done=read(USER,{rounds:{}}).rounds?.[c.sub.id]?.completed||[];$$('#sectionBar [data-section]').forEach(b=>{const sec=(c.sub.sections||[]).find(s=>s.id===b.dataset.section),ids=(sec?.items||[]).map(i=>i.id),ok=ids.length&&ids.every(id=>done.includes(id)),dot=b.querySelector('.v75dot');if(ok&&!dot){const x=document.createElement('span');x.className='v75dot';b.append(x)}else if(!ok&&dot)dot.remove()})}
function ensureDock(){const c=context(),has=$('.reader')||$('.study-card');if(!has||!c){$('#v75dock')?.remove();return}let d=$('#v75dock');if(!d){d=document.createElement('aside');d.id='v75dock';d.innerHTML='<div class="v75head"><span class="v75title">학습 도구</span><button class="v75collapse">‹</button></div><div class="v75body"><button data-m="reader">원문</button><button data-m="mask-edit">가리기 설정</button><button data-m="mask-study">가리기 학습</button><button data-m="typing">타이핑</button><hr><button data-save>임시 저장</button><div id="v75save" class="v75save"></div><button class="complete" data-complete>학습 완료</button></div>';document.body.append(d);d.querySelector('.v75collapse').onclick=()=>{const s=cfg();s.studyDockCollapsed=!d.classList.contains('collapsed');write(SETTINGS,s);dockState();positionDock()};d.querySelector('[data-m="reader"]').onclick=goReader;d.querySelector('[data-m="mask-edit"]').onclick=()=>enter('mask-edit');d.querySelector('[data-m="mask-study"]').onclick=()=>enter('mask-study');d.querySelector('[data-m="typing"]').onclick=()=>enter('typing');d.querySelector('[data-save]').onclick=tempSave;d.querySelector('[data-complete]').onclick=complete}dockState();positionDock();updateDock();updateSave()}
function dockState(){const d=$('#v75dock');if(!d)return;const col=cfg().studyDockCollapsed===true;d.classList.toggle('collapsed',col);d.querySelector('.v75collapse').textContent=col?'›':'‹'}
function positionDock(){const d=$('#v75dock'),card=$('.reader')||$('.study-card');if(!d||!card||innerWidth<=900)return;const r=card.getBoundingClientRect(),w=d.classList.contains('collapsed')?46:184;let left=r.right+14;if(left+w>innerWidth-12)left=Math.max(12,r.right-w-12);d.style.left=`${Math.round(left)}px`;d.style.top=`${Math.max(196,Math.round(r.top))}px`}
function updateDock(){const d=$('#v75dock');if(!d)return;const m=$('.reader')?'reader':currentMode;$$('#v75dock [data-m]').forEach(b=>b.classList.toggle('active',b.dataset.m===m))}
function updateSave(){const c=context(),e=$('#v75save');if(!c||!e)return;const d=read(USER,{drafts:{}}).drafts?.[c.item.id];e.textContent=d?.savedAt?`저장 ${new Date(d.savedAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`:'아직 저장 없음'}
function syncParticleSetting(){const box=$('#particleSelectable');if(!box||box.dataset.v75==='1')return;box.dataset.v75='1';box.checked=cfg().excludeParticles!==false;box.addEventListener('change',()=>{const s=cfg();s.excludeParticles=box.checked;write(SETTINGS,s);if($('.study-card'))renderMode(currentMode)})}
function enhance(){css();if(!$('#v75badge')){const b=document.createElement('div');b.id='v75badge';b.textContent='Study v7.5';document.body.append(b)}if($('.reader'))currentMode='reader';ensureDock();dots();syncParticleSetting()}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance()})}
new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});addEventListener('resize',positionDock);addEventListener('scroll',positionDock,{passive:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
})();
