(() => {
'use strict';
const DATA='tes_curriculum_v5', USER='tes_user_v5', SETTINGS='tes_settings_v5';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??structuredClone(f)}catch{return structuredClone(f)}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let queued=false;
function injectCss(){if($('#v72style'))return;const s=document.createElement('style');s.id='v72style';s.textContent=`
#v72badge{position:fixed;left:10px;bottom:10px;z-index:9999;font:700 10px/1 system-ui;background:#171a21;color:#fff;padding:5px 7px;border-radius:7px;opacity:.55}
.reader .reader-actions,.study-titlebar .mode-switch,.study-card>.study-footer{display:none!important}
#v72dock{position:fixed;z-index:100;width:184px;padding:10px;background:rgba(255,255,255,.98);border:1px solid var(--line);border-radius:15px;box-shadow:0 12px 34px rgba(23,26,33,.14);display:grid;gap:7px;transition:.18s}
#v72dock.collapsed{width:46px;padding:8px 6px}#v72dock.collapsed .v72body,#v72dock.collapsed .v72title{display:none}.v72head{display:flex;align-items:center;justify-content:space-between;gap:6px}.v72title{font-size:12px;color:var(--muted);font-weight:800;padding-left:4px}.v72collapse{border:1px solid var(--line);background:#fff;border-radius:9px;padding:5px 8px;cursor:pointer}.v72body{display:grid;gap:6px}.v72body button{border:1px solid var(--line);background:#fff;color:var(--text);border-radius:10px;padding:9px 10px;text-align:left;font-size:13px}.v72body button.active{background:var(--primary-soft);color:var(--primary);border-color:#dfe5ff;font-weight:700}.v72body button.complete{background:#171a21;color:#fff;border-color:#171a21}.v72body hr{width:100%;border:0;border-top:1px solid var(--line);margin:2px 0}.v72save{font-size:10px;color:var(--muted);padding:1px 4px 3px}
.v72word{display:inline-flex;align-items:baseline;white-space:nowrap}.v72core{margin:2px 1px!important}.v72tail{display:inline!important;background:transparent!important;color:var(--text)!important;opacity:.82;margin-right:2px}.v72group{box-shadow:inset 0 -2px 0 rgba(49,94,251,.5)}
.v72need{margin:14px 0;padding:14px 16px;border:1px solid #f2c94c;background:#fffaf0;border-radius:12px;line-height:1.55}.v72need strong{display:block;margin-bottom:4px}
.mask-study [data-v72-reveal].v72correct{color:var(--text)!important;background:transparent!important;border:2px solid #22c55e!important;box-shadow:0 0 0 3px rgba(34,197,94,.10)!important;padding:2px 5px!important}.mask-study [data-v72-reveal].v72wrong{color:var(--text)!important;background:transparent!important;border:2px solid #ef4444!important;box-shadow:0 0 0 3px rgba(239,68,68,.10)!important;padding:2px 5px!important}
.section-bar .v72dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:#22c55e;margin-left:7px;box-shadow:0 0 0 3px rgba(34,197,94,.12)}
.v72tablewrap{overflow-x:auto;margin:22px 0}.v72caption{font-size:13px;font-weight:750;margin:0 0 8px}.v72table{border-collapse:separate;border-spacing:0;width:100%;min-width:640px;border:1px solid var(--line);border-radius:12px;overflow:hidden;background:#fff}.v72table th,.v72table td{border-right:1px solid var(--line);border-bottom:1px solid var(--line);padding:12px 13px;vertical-align:top;line-height:1.65;white-space:pre-line}.v72table th{background:#f6f7f9;font-weight:800;text-align:center}.v72table tr:last-child>*{border-bottom:0}.v72table tr>*:last-child{border-right:0}
.v72toast{position:fixed;left:50%;bottom:28px;transform:translate(-50%,14px);z-index:130;background:#171a21;color:#fff;padding:10px 14px;border-radius:10px;opacity:0;pointer-events:none;transition:.18s}.v72toast.show{opacity:1;transform:translate(-50%,0)}
@media(max-width:900px){#v72dock{left:12px!important;right:12px!important;top:auto!important;bottom:12px!important;width:auto!important;display:flex;align-items:center;padding:8px}.v72head{flex:0 0 auto}.v72title{display:none}.v72body{display:flex;overflow-x:auto}.v72body hr,.v72save{display:none}.v72body button{white-space:nowrap;flex:0 0 auto;text-align:center}.reader,.study-card{padding-bottom:96px}#v72dock.collapsed{left:auto!important;right:12px!important;width:46px!important}.v72word{white-space:normal}}
`;document.head.append(s)}
function allData(){return read(DATA,{subjects:[]})}
function cfg(){return read(SETTINGS,{})}
function context(){const d=allData();const sm=$('.study-titlebar .eyebrow')?.textContent||'',st=$('.study-titlebar h2')?.textContent?.trim();if(sm&&st){const [sn,secn]=sm.split('·').map(x=>x.trim());for(const sub of d.subjects||[])if(sub.name===sn)for(const sec of sub.sections||[])if(sec.name===secn){const item=(sec.items||[]).find(i=>(i.title||'학습')===st)||sec.items?.[0];if(item)return{sub,sec,item,view:'study'}}}const bc=$('.reader .breadcrumb')?.textContent||'',rt=$('.reader .reader-heading h1')?.textContent?.trim();if(bc&&rt){const [sn,secn]=bc.split('/').map(x=>x.trim());for(const sub of d.subjects||[])if(sub.name===sn)for(const sec of sub.sections||[])if(sec.name===secn){const item=(sec.items||[]).find(i=>(i.title||'교육과정 원문')===rt)||sec.items?.[0];if(item)return{sub,sec,item,view:'reader'}}}return null}
function units(item){return Array.isArray(item?.studyUnits)&&item.studyUnits.length?item.studyUnits:null}
function stFor(item){const all=read(USER,{itemState:{},rounds:{},drafts:{}});all.itemState??={};all.rounds??={};all.drafts??={};all.itemState[item.id]??={masked:[],wrongTokens:[],wrongCount:0,attempts:0,correct:0};const u=all.itemState[item.id];u.masked??=[];u.wrongTokens??=[];all.drafts[item.id]??={};return{all,u,draft:all.drafts[item.id],save:()=>write(USER,all)}}
function ordinals(item,u){const us=units(item);if(!us)return[];const legacy=new Map(us.map((x,i)=>[x.legacyTokenIndex,i]));return[...new Set((u.masked||[]).map(v=>legacy.has(v)?legacy.get(v):(Number.isInteger(v)&&v<us.length?v:null)).filter(v=>v!==null))].sort((a,b)=>a-b)}
function saveOrds(item,u,os){const us=units(item);u.masked=os.map(i=>us[i]?.legacyTokenIndex??i)}
function parts(u){return cfg().excludeParticles===false?{core:u.surface,tail:''}:{core:u.core||u.surface,tail:`${u.particle||''}${u.punctuation||''}`}}
function runs(item,u){const us=units(item),sel=new Set(ordinals(item,u)),out=[];let run=[];const flush=()=>{if(run.length>1)out.push([...run]);run=[]};for(let i=0;i<us.length;i++){if(!sel.has(i)){flush();continue}if(!run.length){run=[i];continue}const p=run.at(-1);if(i===p+1&&us[i].semanticUnit===us[p].semanticUnit)run.push(i);else{flush();run=[i]}}flush();return out}
function needV7(box){box.innerHTML='<div class="v72need"><strong>이 항목은 아직 v7 학습 데이터가 아니에요.</strong>조사 제외와 연속 빈칸 연결을 사용하려면 방금 만든 v7 JSON을 이 과목에 다시 업로드해 주세요.</div>'}
function editorHTML(item,u){const us=units(item),sel=new Set(ordinals(item,u)),gs=runs(item,u);return us.map((x,i)=>{const p=parts(x),g=gs.some(r=>r.includes(i));return `${esc(x.leadingSpace||'')}<span class="v72word"><span class="token selectable v72core${sel.has(i)?' selected':''}${g?' v72group':''}" data-v72-unit="${i}">${esc(p.core)}</span>${p.tail?`<span class="v72tail">${esc(p.tail)}</span>`:''}</span>`}).join('')+esc(us.at(-1)?.trailingSpace||'')}
function setupEditor(box){if(box.dataset.v72==='1')return;const c=context();if(!c)return;const us=units(c.item);box.dataset.v72='1';if(!us)return needV7(box);const st=stFor(c.item),u=st.u,draw=()=>box.innerHTML=editorHTML(c.item,u);draw();box.addEventListener('click',e=>{const el=e.target.closest('[data-v72-unit]');if(!el)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const i=Number(el.dataset.v72Unit),s=new Set(ordinals(c.item,u));s.has(i)?s.delete(i):s.add(i);saveOrds(c.item,u,[...s].sort((a,b)=>a-b));st.save();draw()},true)}
function build(item,u,typing){const us=units(item),sel=new Set(ordinals(item,u)),gs=runs(item,u),first=new Map(gs.map(r=>[r[0],r])),covered=new Set(gs.flat());let out='';for(let i=0;i<us.length;i++){const x=us[i];out+=esc(x.leadingSpace||'');const r=first.get(i);if(r){const vals=r.map(j=>parts(us[j]).core),last=parts(us[r.at(-1)]),exp=vals.join(' '),w=Math.max(120,Math.min(520,exp.length*18+38));out+=typing?`<input class="inline-answer" data-v72-idx="${r.join(',')}" data-v72-exp="${esc(exp)}" style="width:${w}px" autocomplete="off">${last.tail?`<span class="v72tail">${esc(last.tail)}</span>`:''}`:`<span class="token masked" data-v72-reveal="${r.join(',')}">${esc(exp)}</span>${last.tail?`<span class="v72tail">${esc(last.tail)}</span>`:''}`;i=r.at(-1);continue}if(covered.has(i))continue;if(!sel.has(i)){out+=esc(x.surface);continue}const p=parts(x),w=Math.max(76,Math.min(300,p.core.length*22+30));out+=typing?`<input class="inline-answer" data-v72-idx="${i}" data-v72-exp="${esc(p.core)}" style="width:${w}px" autocomplete="off">${p.tail?`<span class="v72tail">${esc(p.tail)}</span>`:''}`:`<span class="token masked" data-v72-reveal="${i}">${esc(p.core)}</span>${p.tail?`<span class="v72tail">${esc(p.tail)}</span>`:''}`;}out+=esc(us.at(-1)?.trailingSpace||'');return out}
function applyFeedback(el,state){el.classList.remove('revealed','v72correct','v72wrong');if(state==='correct')el.classList.add('revealed','v72correct');if(state==='wrong')el.classList.add('revealed','v72wrong')}
function setupMask(box){if(box.dataset.v72==='1')return;const c=context();if(!c)return;box.dataset.v72='1';if(!units(c.item))return needV7(box);const st=stFor(c.item);if(!ordinals(c.item,st.u).length)return;box.innerHTML=build(c.item,st.u,false);st.draft.maskFeedback??={};box.querySelectorAll('[data-v72-reveal]').forEach(el=>{const key=el.dataset.v72Reveal;applyFeedback(el,st.draft.maskFeedback[key]||'hidden');el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const live=stFor(c.item);live.draft.maskFeedback??={};const now=live.draft.maskFeedback[key]||'hidden',ids=key.split(',').map(Number),next=now==='hidden'?'correct':now==='correct'?'wrong':'hidden';live.draft.maskFeedback[key]=next;if(next==='correct')live.u.wrongTokens=(live.u.wrongTokens||[]).filter(x=>!ids.includes(Number(x)));if(next==='wrong'){ids.forEach(i=>{if(!live.u.wrongTokens.some(x=>Number(x)===i))live.u.wrongTokens.push(i)});live.u.wrongCount=(live.u.wrongCount||0)+1}live.save();applyFeedback(el,next)},true)})}
function norm(v){return String(v||'').toLowerCase().replace(/[\s.,!?;:'"“”‘’·⋅()\[\]{}<>/\\\-_~`]+/g,'')}
function setupTyping(box){if(box.dataset.v72==='1')return;const c=context();if(!c)return;box.dataset.v72='1';if(!units(c.item))return needV7(box);const st=stFor(c.item),u=st.u;if(!ordinals(c.item,u).length)return;box.innerHTML=build(c.item,u,true);const ins=[...box.querySelectorAll('.inline-answer')];if(st.draft.typingValues)ins.forEach(i=>{if(i.dataset.v72Idx in st.draft.typingValues)i.value=st.draft.typingValues[i.dataset.v72Idx]});const check=input=>{if(!input.value.trim())return;const exp=input.dataset.v72Exp||'',ids=(input.dataset.v72Idx||'').split(',').map(Number),m=cfg().gradingMode||'flexible',ok=m==='strict'?input.value.trim()===exp.trim():m==='self'?null:norm(input.value)===norm(exp);input.classList.remove('input-correct','input-wrong','input-self');if(ok===null)input.classList.add('input-self');else if(ok){input.classList.add('input-correct');u.wrongTokens=(u.wrongTokens||[]).filter(x=>!ids.includes(Number(x)))}else{input.classList.add('input-wrong');ids.forEach(i=>{if(!u.wrongTokens.some(x=>Number(x)===i))u.wrongTokens.push(i)});input.title=`정답: ${exp}`}st.save()};ins.forEach((i,n)=>{i.onblur=()=>check(i);i.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();check(i);ins[n+1]?.focus()}}})}
function mode(){if($('.reader'))return'reader';return $('.mode-switch [data-mode].active')?.dataset.mode||'mask-edit'}
function go(m){if(m==='reader'){if($('.study-card'))$('#backReaderBtn')?.click();return}if($('.reader')){if(m==='mask-edit')$('#maskStartBtn')?.click();else if(m==='typing')$('#typingStartBtn')?.click();else{$('#maskStartBtn')?.click();setTimeout(()=>document.querySelector('[data-mode="mask-study"]')?.click(),60)}return}document.querySelector(`[data-mode="${m}"]`)?.click()}
function toast(msg){let t=$('#v72toast');if(!t){t=document.createElement('div');t.id='v72toast';t.className='v72toast';document.body.append(t)}t.textContent=msg;t.classList.add('show');clearTimeout(t._);t._=setTimeout(()=>t.classList.remove('show'),1700)}
function tempSave(){const c=context();if(!c)return;const st=stFor(c.item),vals={};$$('.typing-inline .inline-answer').forEach(i=>vals[i.dataset.v72Idx||'']=i.value);st.draft.mode=mode();st.draft.typingValues=vals;st.draft.scrollY=scrollY;st.draft.savedAt=Date.now();st.save();updateSave();toast('현재 학습 상태를 임시 저장했어요.')}
function enabled(sub){const p=cfg().sectionPrefs?.[sub.id]||{};return(sub.sections||[]).filter(sec=>p[sec.id]?.study!==false)}
function complete(){const c=context();if(!c)return;const st=stFor(c.item),r=st.all.rounds[c.sub.id]??={count:0,completed:[]};if(!r.completed.includes(c.item.id))r.completed.push(c.item.id);const all=enabled(c.sub).flatMap(s=>(s.items||[]).map(i=>i.id));if(all.length&&all.every(id=>r.completed.includes(id))){r.count=(r.count||0)+1;r.completed=[];toast(`${c.sub.name} ${r.count}회독 완료!`)}else toast('학습 완료로 저장했어요.');st.save();dots()}
function dots(){const c=context();if(!c)return;const done=read(USER,{rounds:{}}).rounds?.[c.sub.id]?.completed||[];$$('#sectionBar [data-section]').forEach(b=>{const sec=(c.sub.sections||[]).find(s=>s.id===b.dataset.section),ids=(sec?.items||[]).map(i=>i.id),ok=ids.length&&ids.every(id=>done.includes(id)),d=b.querySelector('.v72dot');if(ok&&!d){d=document.createElement('span');d.className='v72dot';b.append(d)}else if(!ok&&d)d.remove()})}
function ensureDock(){const card=$('.reader')||$('.study-card');if(!card){$('#v72dock')?.remove();return}let d=$('#v72dock');if(!d){d=document.createElement('aside');d.id='v72dock';d.innerHTML='<div class="v72head"><span class="v72title">학습 도구</span><button class="v72collapse">‹</button></div><div class="v72body"><button data-v72-mode="reader">원문</button><button data-v72-mode="mask-edit">가리기 설정</button><button data-v72-mode="mask-study">가리기 학습</button><button data-v72-mode="typing">타이핑</button><hr><button data-v72-temp>임시 저장</button><div id="v72save" class="v72save"></div><button class="complete" data-v72-complete>학습 완료</button></div>';document.body.append(d);d.querySelector('.v72collapse').onclick=()=>{const s=cfg();s.studyDockCollapsed=!d.classList.contains('collapsed');write(SETTINGS,s);dockState();positionDock()};d.querySelectorAll('[data-v72-mode]').forEach(b=>b.onclick=()=>go(b.dataset.v72Mode));d.querySelector('[data-v72-temp]').onclick=tempSave;d.querySelector('[data-v72-complete]').onclick=complete}dockState();$$('#v72dock [data-v72-mode]').forEach(b=>b.classList.toggle('active',b.dataset.v72Mode===mode()));updateSave();positionDock()}
function dockState(){const d=$('#v72dock');if(!d)return;const c=cfg().studyDockCollapsed===true;d.classList.toggle('collapsed',c);d.querySelector('.v72collapse').textContent=c?'›':'‹'}
function positionDock(){const d=$('#v72dock'),card=$('.reader')||$('.study-card');if(!d||!card||innerWidth<=900)return;const r=card.getBoundingClientRect(),w=d.classList.contains('collapsed')?46:184;let left=r.right+14;if(left+w>innerWidth-12)left=Math.max(12,r.right-w-12);d.style.left=`${Math.round(left)}px`;d.style.right='auto';d.style.top=`${Math.max(196,Math.round(r.top))}px`}
function updateSave(){const c=context(),el=$('#v72save');if(!el)return;if(!c){el.textContent='';return}const d=read(USER,{drafts:{}}).drafts?.[c.item.id];el.textContent=d?.savedAt?`임시 저장 ${new Date(d.savedAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}`:'아직 임시 저장 없음'}
function renderTable(b){const occ=new Set(),map=new Map((b.cells||[]).map(c=>[`${c.row}:${c.col}`,c])),ws=b.columnWidths||[];let h='<div class="v72tablewrap">';if(b.caption)h+=`<div class="v72caption">${esc(b.caption)}</div>`;h+='<table class="v72table"><colgroup>'+Array.from({length:b.cols||0},(_,i)=>`<col style="width:${Math.round((ws[i]||1/(b.cols||1))*10000)/100}%">`).join('')+'</colgroup><tbody>';for(let r=0;r<(b.rows||0);r++){h+='<tr>';for(let c=0;c<(b.cols||0);c++){if(occ.has(`${r}:${c}`))continue;const cell=map.get(`${r}:${c}`);if(!cell){h+='<td></td>';continue}for(let rr=r;rr<r+(cell.rowspan||1);rr++)for(let cc=c;cc<c+(cell.colspan||1);cc++)if(rr!==r||cc!==c)occ.add(`${rr}:${cc}`);const tag=cell.header||r<(b.headerRows||0)?'th':'td',txt=(cell.segments||[{text:cell.text||''}]).map(s=>esc(s.text)).join('');h+=`<${tag} rowspan="${cell.rowspan||1}" colspan="${cell.colspan||1}">${txt}</${tag}>`}h+='</tr>'}return h+'</tbody></table></div>'}
function tables(){const c=context();if(!c||c.view!=='reader')return;const bs=(c.item.blocks||[]).filter(b=>b.type==='table'),els=$$('.reader .table-scroll');els.forEach((el,i)=>{const b=bs[i];if(!b||b.tableVersion!==7||el.dataset.v72)return;const x=document.createElement('div');x.innerHTML=renderTable(b);const n=x.firstElementChild;n.dataset.v72='1';el.replaceWith(n)})}
function syncSetting(){const b=$('#particleSelectable');if(b)b.checked=cfg().excludeParticles!==false}
document.addEventListener('change',e=>{if(e.target?.id==='particleSelectable'){const s=cfg();s.excludeParticles=e.target.checked;write(SETTINGS,s);$$('.token-editor,.mask-study,.typing-inline').forEach(x=>delete x.dataset.v72);schedule()}},true);
document.addEventListener('click',e=>{if(e.target.closest('#settingsBtn'))setTimeout(syncSetting,0);if(e.target.closest('#saveSettingsBtn')){const val=$('#particleSelectable')?.checked!==false;setTimeout(()=>{const s=cfg();s.excludeParticles=val;write(SETTINGS,s)},40)}},true);
function enhance(){injectCss();if(!$('#v72badge')){const b=document.createElement('div');b.id='v72badge';b.textContent='Study v7.2';document.body.append(b)}ensureDock();dots();tables();const e=$('.token-editor');if(e)setupEditor(e);const m=$('.mask-study');if(m)setupMask(m);const t=$('.typing-inline');if(t)setupTyping(t)}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance()})}
new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});addEventListener('resize',positionDock);addEventListener('scroll',positionDock,{passive:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
})();