(() => {
'use strict';
const D='tes_curriculum_v5',U='tes_user_v5';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??structuredClone(f)}catch{return structuredClone(f)}},esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const DATA=read(D,{subjects:[]}),itemMap=new Map();for(const sub of DATA.subjects||[])for(const sec of sub.sections||[])for(const item of sec.items||[])itemMap.set(item.id,{sub,sec,item});let weakSid=null,queued=false;
const units=i=>Array.isArray(i?.studyUnits)?i.studyUnits:[];
function css(){if($('#v761weakStyle'))return;const s=document.createElement('style');s.id='v761weakStyle';s.textContent=`#weaknessBtn{display:none!important}.v761weak-count{display:inline-flex;align-items:center;justify-content:center;min-width:18px;height:18px;padding:0 5px;margin-left:5px;border-radius:999px;background:#ef4444;color:#fff;font-size:10px;font-weight:800}.v761weak-page{max-width:1100px;margin:0 auto;padding:24px 0 110px}.v761weak-head{margin-bottom:18px}.v761weak-head h1{margin:5px 0}.v761weak-area{margin-bottom:22px}.v761weak-area>h2{font-size:18px;margin:0 0 10px}.v761weak-list{display:grid;gap:10px}.v761weak-card{padding:16px 18px}.v761weak-meta{font-size:12px;color:var(--muted);margin-bottom:8px}.v761weak-text{white-space:pre-wrap;line-height:1.75}.v761weak-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.v761weak-empty{padding:42px;text-align:center;color:var(--muted)}@media(max-width:700px){.v761weak-page{padding-left:12px;padding-right:12px}.v761weak-card{padding:14px}.v761weak-text{font-size:13px;line-height:1.7}.v761weak-actions button{font-size:12px;padding:8px 10px}}`;document.head.append(s)}
function semanticText(item,sem){const a=units(item).filter(u=>u.semanticUnit===sem);return a.map(u=>`${u.leadingSpace||''}${u.surface||''}`).join('')+(a.at(-1)?.trailingSpace||'')}
function roundInfo(sid){const a=read(U,{rounds:{}}),count=Number(a.rounds?.[sid]?.count||0);return{key:String(count),label:`${count+1}회독`}}
function entries(sid){const a=read(U,{itemState:{},rounds:{}}),rk=String(Number(a.rounds?.[sid]?.count||0)),out=[];for(const[id,s]of Object.entries(a.itemState||{})){const f=itemMap.get(id);if(!f||f.sub.id!==sid)continue;for(const sem of s.weakByRound?.[rk]||[])out.push({...f,semanticUnit:sem,text:semanticText(f.item,sem)})}return out}
function currentSid(){const active=$('#subjectBar [data-subject].active')?.dataset.subject;if(active)return active;return weakSid}
function tab(){const bar=$('#sectionBar'),sid=currentSid();if(!bar||!sid)return;if(!bar.querySelector('[data-section]')&&!weakSid)return;let b=bar.querySelector('[data-v761-weak]');if(!b){bar.querySelector('[data-v76-weak]')?.remove();b=document.createElement('button');b.className='nav-tab';b.dataset.v761Weak='1';bar.appendChild(b)}const n=entries(sid).length;b.innerHTML=`약점 보충${n?` <span class="v761weak-count">${n}</span>`:''}`;b.onclick=()=>render(sid);if(weakSid===sid&&$('#appMain .v761weak-page'))$$('#sectionBar .nav-tab').forEach(x=>x.classList.toggle('active',x===b))}
function render(sid){weakSid=sid;const sub=(DATA.subjects||[]).find(s=>s.id===sid);if(!sub)return;tab();$$('#sectionBar .nav-tab').forEach(x=>x.classList.toggle('active',x.hasAttribute('data-v761-weak')));const es=entries(sid),by=new Map(),ri=roundInfo(sid);for(const e of es){if(!by.has(e.sec.id))by.set(e.sec.id,{sec:e.sec,rows:[]});by.get(e.sec.id).rows.push(e)}$('#appMain').innerHTML=`<section class="v761weak-page"><div class="v761weak-head"><span class="eyebrow">${esc(sub.name)} · ${esc(ri.label)}</span><h1>약점 보충</h1><p><strong>이번 회독에서 한 번이라도 틀린</strong> 빈칸이 포함된 선 사이 전체만 모았습니다. 다시 맞혀도 이 회독이 끝날 때까지 유지됩니다.</p></div>${es.length?[...by.values()].map(g=>`<section class="v761weak-area"><h2>${esc(g.sec.name)} <small>(${g.rows.length})</small></h2><div class="v761weak-list">${g.rows.map(e=>`<article class="card v761weak-card"><div class="v761weak-meta">${esc(e.item.title||'교육과정 원문')}</div><div class="v761weak-text">${esc(e.text)}</div><div class="v761weak-actions"><button class="primary-btn" data-v761-mask="${esc(e.item.id)}" data-sem="${esc(e.semanticUnit)}">가리기 학습</button><button class="ghost-btn" data-v761-type="${esc(e.item.id)}" data-sem="${esc(e.semanticUnit)}">타이핑 학습</button><button class="ghost-btn" data-v761-open="${esc(e.item.id)}">원문 보기</button></div></article>`).join('')}</div></section>`).join(''):'<div class="card v761weak-empty">이번 회독에서 아직 틀린 항목이 없습니다.</div>'}</section>`;$$('[data-v761-mask]').forEach(b=>b.onclick=()=>study(b.dataset.v761Mask,b.dataset.sem,'mask-study'));$$('[data-v761-type]').forEach(b=>b.onclick=()=>study(b.dataset.v761Type,b.dataset.sem,'typing'));$$('[data-v761-open]').forEach(b=>b.onclick=()=>open(b.dataset.v761Open))}
function study(id,sem,m){const f=itemMap.get(id);if(!f)return;window.TESV76Study?.open({subjectId:f.sub.id,sectionId:f.sec.id,itemId:f.item.id},m,sem)}
function open(id){const f=itemMap.get(id);if(!f)return;$(`#subjectBar [data-subject="${CSS.escape(f.sub.id)}"]`)?.click();setTimeout(()=>{$(`#sectionBar [data-section="${CSS.escape(f.sec.id)}"]`)?.click();setTimeout(()=>{$(`[data-item="${CSS.escape(f.item.id)}"]`)?.click()},50)},50);weakSid=null}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;tab()})}
function observe(){const bar=$('#sectionBar'),main=$('#appMain');if(bar)new MutationObserver(schedule).observe(bar,{childList:true});if(main)new MutationObserver(schedule).observe(main,{childList:true})}
css();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{tab();observe()});else{tab();observe()}
document.addEventListener('click',e=>{if(e.target.closest('[data-subject],[data-section],#homeBtn,#tableLibraryBtn')){if(!e.target.closest('[data-v761-weak]'))weakSid=null;setTimeout(schedule,0)}},true);
window.addEventListener('tes:weakness-updated',schedule);
})();