(() => {
'use strict';
const DATA='tes_curriculum_v5', USER='tes_user_v5';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??structuredClone(f)}catch{return structuredClone(f)}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let queued=false, weaknessView=false;
function css(){if($('#v752weakStyle'))return;const s=document.createElement('style');s.id='v752weakStyle';s.textContent=`#weaknessBtn{display:none!important}.v752weak-btn{position:relative}.v752weak-count{display:inline-flex;align-items:center;justify-content:center;min-width:20px;height:20px;padding:0 6px;margin-left:6px;border-radius:999px;background:#ef4444;color:#fff;font-size:11px;font-weight:800}.v752weak-page{max-width:1100px;margin:0 auto;padding:24px 0 50px}.v752weak-head{margin-bottom:18px}.v752weak-head h1{margin:5px 0}.v752weak-area{margin-bottom:20px}.v752weak-area>h2{font-size:18px;margin:0 0 10px}.v752weak-list{display:grid;gap:10px}.v752weak-card{padding:16px 18px}.v752weak-meta{font-size:12px;color:var(--muted);margin-bottom:7px}.v752weak-text{white-space:pre-wrap;line-height:1.75}.v752weak-actions{display:flex;gap:8px;margin-top:12px}.v752weak-empty{padding:42px;text-align:center;color:var(--muted)}`;document.head.append(s)}
function allData(){return read(DATA,{subjects:[]})}
function findItem(itemId){for(const sub of allData().subjects||[])for(const sec of sub.sections||[])for(const item of sec.items||[])if(item.id===itemId)return{sub,sec,item};return null}
function currentContext(){const bc=$('.reader .breadcrumb')?.textContent||'',rt=$('.reader .reader-heading h1')?.textContent?.trim(),sm=$('.study-titlebar .eyebrow')?.textContent||'',st=$('.study-titlebar h2')?.textContent?.trim(),d=allData();if(bc&&rt){const [sn,secn]=bc.split('/').map(x=>x.trim());for(const sub of d.subjects||[])if(sub.name===sn)for(const sec of sub.sections||[])if(sec.name===secn){const item=(sec.items||[]).find(i=>(i.title||'교육과정 원문')===rt)||sec.items?.[0];if(item)return{sub,sec,item}}}if(sm&&st){const [sn,secn]=sm.split('·').map(x=>x.trim());for(const sub of d.subjects||[])if(sub.name===sn)for(const sec of sub.sections||[])if(sec.name===secn){const item=(sec.items||[]).find(i=>(i.title||'학습')===st)||sec.items?.[0];if(item)return{sub,sec,item}}}const active=$('#subjectBar [data-subject].active')?.dataset.subject,sub=(d.subjects||[]).find(s=>s.id===active);return sub?{sub,sec:null,item:null}:null}
function units(item){return Array.isArray(item?.studyUnits)?item.studyUnits:[]}
function semanticText(item,semanticUnit){const us=units(item).filter(u=>u.semanticUnit===semanticUnit);return us.map(u=>`${u.leadingSpace||''}${u.surface||''}`).join('')+(us.at(-1)?.trailingSpace||'')}
function semanticForIds(item,ids){const us=units(item);return[...new Set(ids.map(i=>us[i]?.semanticUnit).filter(Boolean))]}
function legacyToOrdinal(item,val){const us=units(item);let i=us.findIndex(u=>u.legacyTokenIndex===val);if(i<0&&Number.isInteger(val)&&val>=0&&val<us.length)i=val;return i}
function syncWeakSections(){const all=read(USER,{itemState:{}});all.itemState??={};let changed=false;for(const [itemId,u] of Object.entries(all.itemState)){const found=findItem(itemId);if(!found)continue;u.weakSemanticUnits??=[];const ords=(u.wrongTokens||[]).map(v=>legacyToOrdinal(found.item,Number(v))).filter(i=>i>=0),sems=semanticForIds(found.item,ords);for(const sem of sems)if(!u.weakSemanticUnits.includes(sem)){u.weakSemanticUnits.push(sem);changed=true}}if(changed)write(USER,all)}
function addWeak(item,ids){const all=read(USER,{itemState:{}});all.itemState??={};all.itemState[item.id]??={};const u=all.itemState[item.id];u.weakSemanticUnits??=[];for(const sem of semanticForIds(item,ids))if(!u.weakSemanticUnits.includes(sem))u.weakSemanticUnits.push(sem);write(USER,all)}
function removeWeakIfClean(item,sem){const all=read(USER,{itemState:{}}),u=all.itemState?.[item.id];if(!u)return;u.weakSemanticUnits??=[];const us=units(item),wrong=new Set((u.wrongTokens||[]).map(Number)),stillWrong=us.some((x,i)=>x.semanticUnit===sem&&wrong.has(Number(x.legacyTokenIndex??i)));if(!stillWrong)u.weakSemanticUnits=u.weakSemanticUnits.filter(x=>x!==sem);write(USER,all)}
function observeAnswers(){document.addEventListener('click',e=>{const el=e.target.closest('[data-v75-reveal]');if(!el)return;setTimeout(()=>{const c=currentContext();if(!c?.item)return;const ids=(el.dataset.v75Reveal||'').split(',').map(Number).filter(Number.isFinite);if(el.classList.contains('v75wrong'))addWeak(c.item,ids);if(el.classList.contains('v75correct'))for(const sem of semanticForIds(c.item,ids))removeWeakIfClean(c.item,sem);updateDockCount()},0)},false);document.addEventListener('focusout',e=>{const input=e.target.closest?.('.inline-answer[data-v75-idx]');if(!input)return;setTimeout(()=>{const c=currentContext();if(!c?.item)return;const ids=(input.dataset.v75Idx||'').split(',').map(Number).filter(Number.isFinite);if(input.classList.contains('input-wrong'))addWeak(c.item,ids);if(input.classList.contains('input-correct'))for(const sem of semanticForIds(c.item,ids))removeWeakIfClean(c.item,sem);updateDockCount()},0)},true)}
function entriesForSubject(subjectId){syncWeakSections();const all=read(USER,{itemState:{}}),out=[];for(const [itemId,u] of Object.entries(all.itemState||{})){const f=findItem(itemId);if(!f||f.sub.id!==subjectId)continue;for(const sem of u.weakSemanticUnits||[])out.push({...f,semanticUnit:sem,text:semanticText(f.item,sem)})}return out}
function ensureDockButton(){const dock=$('#v75dock .v75body'),c=currentContext();if(!dock||!c?.sub){$('.v752weak-btn')?.remove();return}let b=dock.querySelector('.v752weak-btn');if(!b){b=document.createElement('button');b.className='v752weak-btn';b.innerHTML='약점 보충 <span class="v752weak-count">0</span>';const hr=dock.querySelector('hr');dock.insertBefore(b,hr||dock.firstChild)}b.dataset.subjectId=c.sub.id;b.onclick=()=>renderWeakness(b.dataset.subjectId);updateDockCount()}
function updateDockCount(){const b=$('.v752weak-btn');if(!b)return;const n=entriesForSubject(b.dataset.subjectId).length,badge=b.querySelector('.v752weak-count');badge.textContent=n;badge.style.display=n?'inline-flex':'none'}
function renderWeakness(subjectId){weaknessView=true;const sub=(allData().subjects||[]).find(s=>s.id===subjectId);if(!sub)return;const entries=entriesForSubject(subjectId),by=new Map();for(const e of entries){if(!by.has(e.sec.id))by.set(e.sec.id,{sec:e.sec,items:[]});by.get(e.sec.id).items.push(e)}$('#sectionBar').innerHTML='';$('#appMain').innerHTML=`<section class="v752weak-page"><div class="v752weak-head"><span class="eyebrow">${esc(sub.name)}</span><h1>약점 보충</h1><p>가리기·타이핑에서 틀린 빈칸이 포함된 의미 섹션 전체를 영역별로 모았습니다.</p></div>${entries.length?[...by.values()].map(g=>`<section class="v752weak-area"><h2>${esc(g.sec.name)} <small>(${g.items.length})</small></h2><div class="v752weak-list">${g.items.map(e=>`<article class="card v752weak-card"><div class="v752weak-meta">${esc(e.item.title||'교육과정 원문')}</div><div class="v752weak-text">${esc(e.text)}</div><div class="v752weak-actions"><button class="ghost-btn" data-v752-open="${esc(e.item.id)}">원문 보기</button></div></article>`).join('')}</div></section>`).join(''):'<div class="card v752weak-empty">이 과목에는 아직 약점 섹션이 없습니다.</div>'}</section>`;$$('[data-v752-open]').forEach(b=>b.onclick=()=>openItem(b.dataset.v752Open))}
function openItem(itemId){const f=findItem(itemId);if(!f)return;$(`#subjectBar [data-subject="${CSS.escape(f.sub.id)}"]`)?.click();setTimeout(()=>{$(`#sectionBar [data-section="${CSS.escape(f.sec.id)}"]`)?.click();setTimeout(()=>{$(`[data-item="${CSS.escape(f.item.id)}"]`)?.click()},30)},30);weaknessView=false}
function navReset(e){if(e.target.closest('#homeBtn,[data-subject],[data-section],[data-item],#tableLibraryBtn'))weaknessView=false}
function enhance(){css();syncWeakSections();ensureDockButton()}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance()})}
observeAnswers();document.addEventListener('click',navReset,true);new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
})();