(() => {
'use strict';
const D='tes_curriculum_v5',U='tes_user_v5';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??structuredClone(f)}catch{return structuredClone(f)}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const DATA=read(D,{subjects:[]}),itemMap=new Map();for(const sub of DATA.subjects||[])for(const sec of sub.sections||[])for(const item of sec.items||[])itemMap.set(item.id,{sub,sec,item});let weakSid=null,queued=false;
const units=i=>Array.isArray(i?.studyUnits)?i.studyUnits:[];
function css(){if($('#v76weakStyle'))return;const s=document.createElement('style');s.id='v76weakStyle';s.textContent=`#weaknessBtn{display:none!important}.v76weak-count{display:inline-flex;align-items:center;justify-content:center;min-width:18px;height:18px;padding:0 5px;margin-left:5px;border-radius:999px;background:#ef4444;color:#fff;font-size:10px;font-weight:800}.v76weak-page{max-width:1100px;margin:0 auto;padding:24px 0 110px}.v76weak-head{margin-bottom:18px}.v76weak-head h1{margin:5px 0}.v76weak-area{margin-bottom:22px}.v76weak-area>h2{font-size:18px;margin:0 0 10px}.v76weak-list{display:grid;gap:10px}.v76weak-card{padding:16px 18px}.v76weak-meta{font-size:12px;color:var(--muted);margin-bottom:8px}.v76weak-text{white-space:pre-wrap;line-height:1.75}.v76weak-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.v76weak-empty{padding:42px;text-align:center;color:var(--muted)}@media(max-width:700px){.v76weak-page{padding-left:12px;padding-right:12px}.v76weak-card{padding:14px}.v76weak-text{font-size:13px;line-height:1.7}.v76weak-actions button{font-size:12px;padding:8px 10px}}`;document.head.append(s)}
function semanticText(item,sem){const a=units(item).filter(u=>u.semanticUnit===sem);return a.map(u=>`${u.leadingSpace||''}${u.surface||''}`).join('')+(a.at(-1)?.trailingSpace||'')}
function ordinal(item,v){const us=units(item);let i=us.findIndex(x=>Number(x.legacyTokenIndex)===Number(v));if(i<0&&Number(v)>=0&&Number(v)<us.length)i=Number(v);return i}
function sync(){const a=read(U,{itemState:{}});a.itemState??={};let ch=false;for(const[id,s]of Object.entries(a.itemState)){const f=itemMap.get(id);if(!f)continue;s.weakSemanticUnits??=[];for(const v of s.wrongTokens||[]){const i=ordinal(f.item,v),sem=units(f.item)[i]?.semanticUnit;if(sem&&!s.weakSemanticUnits.includes(sem)){s.weakSemanticUnits.push(sem);ch=true}}}if(ch)write(U,a)}
function entries(sid){const a=read(U,{itemState:{}}),out=[];for(const[id,s]of Object.entries(a.itemState||{})){const f=itemMap.get(id);if(!f||f.sub.id!==sid)continue;for(const sem of s.weakSemanticUnits||[])out.push({...f,semanticUnit:sem,text:semanticText(f.item,sem)})}return out}
function currentSid(){const active=$('#subjectBar [data-subject].active')?.dataset.subject;if(active)return active;return weakSid}
function tab(){const bar=$('#sectionBar'),sid=currentSid();if(!bar||!sid)return;if(!bar.querySelector('[data-section]')&&!weakSid)return;let b=bar.querySelector('[data-v76-weak]');if(!b){b=document.createElement('button');b.className='nav-tab';b.dataset.v76Weak='1';bar.appendChild(b)}const n=entries(sid).length;b.innerHTML=`약점 보충${n?` <span class="v76weak-count">${n}</span>`:''}`;b.onclick=()=>render(sid);if(weakSid===sid&&$('#appMain .v76weak-page'))$$('#sectionBar .nav-tab').forEach(x=>x.classList.toggle('active',x===b))}
function render(sid){weakSid=sid;const sub=(DATA.subjects||[]).find(s=>s.id===sid);if(!sub)return;tab();$$('#sectionBar .nav-tab').forEach(x=>x.classList.toggle('active',x.hasAttribute('data-v76-weak')));const es=entries(sid),by=new Map();for(const e of es){if(!by.has(e.sec.id))by.set(e.sec.id,{sec:e.sec,rows:[]});by.get(e.sec.id).rows.push(e)}$('#appMain').innerHTML=`<section class="v76weak-page"><div class="v76weak-head"><span class="eyebrow">${esc(sub.name)}</span><h1>약점 보충</h1><p>가리기·타이핑에서 틀린 빈칸이 포함된 선 사이 전체만 모았습니다.</p></div>${es.length?[...by.values()].map(g=>`<section class="v76weak-area"><h2>${esc(g.sec.name)} <small>(${g.rows.length})</small></h2><div class="v76weak-list">${g.rows.map(e=>`<article class="card v76weak-card"><div class="v76weak-meta">${esc(e.item.title||'교육과정 원문')}</div><div class="v76weak-text">${esc(e.text)}</div><div class="v76weak-actions"><button class="primary-btn" data-v76-mask="${esc(e.item.id)}" data-sem="${esc(e.semanticUnit)}">가리기 학습</button><button class="ghost-btn" data-v76-type="${esc(e.item.id)}" data-sem="${esc(e.semanticUnit)}">타이핑 학습</button><button class="ghost-btn" data-v76-open="${esc(e.item.id)}">원문 보기</button></div></article>`).join('')}</div></section>`).join(''):'<div class="card v76weak-empty">이 과목에는 아직 약점이 없습니다.</div>'}</section>`;$$('[data-v76-mask]').forEach(b=>b.onclick=()=>study(b.dataset.v76Mask,b.dataset.sem,'mask-study'));$$('[data-v76-type]').forEach(b=>b.onclick=()=>study(b.dataset.v76Type,b.dataset.sem,'typing'));$$('[data-v76-open]').forEach(b=>b.onclick=()=>open(b.dataset.v76Open))}
function study(id,sem,m){const f=itemMap.get(id);if(!f)return;window.TESV76Study?.open({subjectId:f.sub.id,sectionId:f.sec.id,itemId:f.item.id},m,sem)}
function open(id){const f=itemMap.get(id);if(!f)return;$(`#subjectBar [data-subject="${CSS.escape(f.sub.id)}"]`)?.click();setTimeout(()=>{$(`#sectionBar [data-section="${CSS.escape(f.sec.id)}"]`)?.click();setTimeout(()=>{$(`[data-item="${CSS.escape(f.item.id)}"]`)?.click()},50)},50);weakSid=null}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;tab()})}
css();sync();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{tab();new MutationObserver(schedule).observe($('#sectionBar')||document.body,{childList:true});new MutationObserver(schedule).observe($('#appMain')||document.body,{childList:true})});else{tab();new MutationObserver(schedule).observe($('#sectionBar')||document.body,{childList:true});new MutationObserver(schedule).observe($('#appMain')||document.body,{childList:true})}
document.addEventListener('click',e=>{if(e.target.closest('[data-subject],[data-section],#homeBtn,#tableLibraryBtn')){if(!e.target.closest('[data-v76-weak]'))weakSid=null;setTimeout(schedule,0)}},true);
})();